### ISSUE TITLE
redacted / unredacted - redactedIfAvailable / unredactedIfAvailable support

### ISSUE THREAD

**Issue by Brett-Best** [SwiftUIX/SwiftUIX#103]
Are you interested in adding redactedIfAvailable / unredactedIfAvailable functions?
I can make a PR.

**Comment by vmanot** [comment]
@Brett-Best that'd be great. If you do, however, please make sure you gate them with `#if swift(>=5.3)`, because the current Xcode GM will not compile the code even if you mark the functions with an availability modifier.

**Comment by Brett-Best** [comment]
@vmanot I’ll try and get something ready in the next couple of days (:
