### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kaich** [SwiftUIX/SwiftUIX#106]
xcode : Version 11.2.1
swift 5 

It doesn't compile complete. 

File: `UIViewControllerLifecycleEvent.swift`

```
    func makeUIViewController(context: Context) -> UIViewControllerType {
        UIViewControllerType()
    }
```

Error: `Cannot invoke initializer for type '_UIViewControllerLifecycleEventView<Content>.UIViewControllerType' with no arguments`

**Comment by vmanot** [comment]
SwiftUIX only supports the latest Xcode GM, can you update to Xcode 11.6?

**Comment by kaich** [comment]
Sorry for so late replay. I update to Version 11.6. It works fine. Thanks

**Comment by vmanot** [comment]
@kaich no worries, glad it works for you now :)
