### ISSUE TITLE
IntrinsicGeometryReader explanation

### ISSUE THREAD

**Issue by tklightningfast** [SwiftUIX/SwiftUIX#112]
Hey! Thanks for the great repository. I noticed that it contains something called an `IntrinsicGeometryReader`, which sounds like what I'm looking for but I'm a little lost in how to use it. The wiki says TBD, so I figured I'd ask about it here. I'm looking for a long-form text editor. The new SwiftUI Beta introduced `TextEditor` which is kind of what I'm looking for, but the content takes up the maximum height it can instead of wrapping to the text. 

Will `IntrinisicGeometryReader` let me have access to the content size of the text, so I can place the `TextEditor` in a frame that wraps to the size of the text?

**Comment by vmanot** [comment]
@tklightningfast I'm not sure whether `IntrinsicGeometryReader` can help you in this particular case - it's meant to read the frame of the view that you wrap with it. The word "intrinsic" may be confusing coming from a UIKit background, but `IntrinsicGeometryReader` doesn't use UIKit's `intrinsicContentSize` concept.

You _could_ render a hidden `Text` and then use its acquired frame to set the `TextEditor`'s frame - but I personally haven't tried it. 

Regardless, thank you for the documentation request, [here you go](https://github.com/SwiftUIX/SwiftUIX/wiki/IntrinsicGeometryReader) :)
