### ISSUE TITLE
OptionalObservableObject is not updating the view.

### ISSUE THREAD

**Issue by lorenzofiamingo** [SwiftUIX/SwiftUIX#113]
When I update a value inside the object, the view is not updating.
If I replace it when the SwiftUI ObservableObject it works.
I'm using iOS 14, XCode 12 beta

	@main
	struct TestAppApp: App {
		
		@OptionalObservedObject private var counter = Counter()
		
		var body: some Scene {
			WindowGroup {
				VStack {
					Text("\(counter?.clock ?? 0)")
						.onAppear {
							counter?.start()
						}
				}.frame(width: 500, height: 300)
			}
		}
	}

**Comment by vmanot** [comment]
@lorenzofiamingo I'll take a look, thank you for bringing this to my attention!

**Comment by vmanot** [comment]
@lorenzofiamingo closing thanks to your fix :)
