### ISSUE TITLE
Set PageControl tint colors 

### ISSUE THREAD

**Issue by Neilpoulin** [SwiftUIX/SwiftUIX#116]
I've looked in the source code and there seem to be a few API methods to set the `pageIndicatorTintColor` and `currentPageIndicatorTintColor`, but I haven't been able to get the color to actually change. 

I've tried a number of things, including setting the environment key. Below is one example of how I've tried. I also tried adding these modifiers to various levels of the view hierarchy, with no luck. What am I missing? 

```swift
                PaginationView(axis: .horizontal) {
                    ForEach(self.items) { feature in
                        ScrollView(.vertical) {
                            FeatureItem(icon: feature.icon!,
                                        title: feature.titleMarkdown!,
                                        description: feature.descriptionMarkdown!)
                            .padding()
                        }
                    }
                }.pageIndicatorTintColor(CustomColors.darkestGreen.color) // makes a swiftUI color
                .currentPageIndicatorTintColor(CustomColors.green.color) // makes a swiftUI color
                .environment(\.currentPageIndicatorTintColor, CustomColors.darkestGreen.color)
                .environment(\.pageIndicatorTintColor, CustomColors.green.color)
```

**Comment by vmanot** [comment]
@Neilpoulin which version of Xcode & iOS are you on?

**Comment by Neilpoulin** [comment]
Xcode 11.6 
iOS 13.6 (simulator)

**Comment by vmanot** [comment]
@Neilpoulin I think it's the custom `Color` → `UIColor` conversion that isn't working. On iOS 13, SwiftUIX resorts to an imperfect hack, `Color` → `UIColor` was only introduced recently with iOS 14, unfortunately :(

**Comment by Neilpoulin** [comment]
Interesting. I use `UIColor -> SwiftUI.Color` (via the CustomColors) in many places in the code and it's worked great, so didn't think to try something different here. 

I was able to set the colors successfully when using a native SwiftUI color. An example is below to help anyone that may come across this issue later.

```swift 
               PaginationView(axis: .horizontal) {
                    ForEach(self.items) { feature in
                        ScrollView(.vertical) {
                            FeatureItem(icon: feature.icon!,
                                        title: feature.titleMarkdown!,
                                        description: feature.descriptionMarkdown!)
                            .padding()
                        }
                    }
                }.pageIndicatorTintColor(Color.blue)
                .currentPageIndicatorTintColor(Color.red) 

```

**Comment by vmanot** [comment]
@Neilpoulin you're talking about `UIColor` → `Color`. I'm talking the other way round :)

I need it in my view representables, but it's not officially available.

**Comment by Neilpoulin** [comment]
Oh, I think I get you now. 

Maybe there could be an separate API method to set the UIColor color directly, so you don't need to do the conversion? I can see how that would complicate things though...

**Comment by Neilpoulin** [comment]
Wanted to leave a followup comment for how I got this working with any color I wanted: use Named Colors from an Asset Catalog. The "hack" that @vmanot mentioned looks like it has a fallback to try to use a Named Color if available. In my case, most of my colors were already named and in the Asset catalog, but not all (including the couple I tried to use initially). 

Everything is working great now. Thanks!

**Comment by vmanot** [comment]
@Neilpoulin great find!

**Comment by IkerSolozabal** [comment]
private func setUpAppearence() {
        UIPageControl.appearance().currentPageIndicatorTintColor = UIColor(Color(colors: appViewConfig.appColor))
        UIPageControl.appearance().pageIndicatorTintColor = UIColor.black.withAlphaComponent(0.2)
    }
