### ISSUE TITLE
Xcode 12 Beta 4: Fails to compile on `PerformActionOnKeyboardShortcut`

### ISSUE THREAD

**Issue by prasannag** [SwiftUIX/SwiftUIX#118]
In `PerformActionOnKeyboardShortcut.swift`, compilation fails with 

> KeyboardShortcut is unavailable 
> 'KeyEquivalent' is unavailable in iOS

This used to compile up until beta 3. I have checked release notes on beta 4, but there is no mention of changes to these APIs.

**Comment by vmanot** [comment]
@prasannag this should be fixed now - please update SwiftUIX to the latest commit :)
