### ISSUE TITLE
How to add animation when adding and deleting items in CocoaList

### ISSUE THREAD

**Issue by fatbobman** [SwiftUIX/SwiftUIX#125]
How to make cocoaList add and delete items dynamically. Can animation be used? I have no experience with uitableview. I don’t know where to make changes.

**Comment by vmanot** [comment]
@fatbobman I'd love to look at it and improve the API - but I'm completely swamped with other work right now :( 

If you want, I can help guide you to understand what would need to be changed.

**Comment by fatbobman** [comment]
If I can get your guidance, I would like to try to make some changes by myself. I read a bit of information. If you want to use animation in uitableview to insert, delete or update data, you must explicitly operate on the data of the operation. For example:
insertRows(at indexPaths: [IndexPath],
            with animation: UITableView.RowAnimation)
Since the data is passed to cocoaList as a whole, how do I find out which data has changed?

**Comment by vmanot** [comment]
@fatbobman extremely sorry for the late reply, last month was crazy. You can reach out to me at vatsal.manot@yahoo.com (iMessage) - and we can discuss this further :)
