### ISSUE TITLE
ObservableBinding for @Binding

### ISSUE THREAD

**Issue by ghost** [SwiftUIX/SwiftUIX#126]
Do we have a wrapper for @Binding with similar function as `@ObservableState`?  So we can get notified when @Binding value changes (also including previous value)

**Comment by vmanot** [comment]
Yep, it's called `@ObservedValue`. It wraps a reference writable key path on an `ObservableObject` - and is passable from view to view similar to `@Binding`.

**Comment by BugMonkey** [comment]
how to use @ObservableState  ? is it like StateObject in iOS13?
