### ISSUE TITLE
Provide a sample app to show the usage of Some UI elements

### ISSUE THREAD

**Issue by michaelkroll** [SwiftUIX/SwiftUIX#13]
It would be helpful to provide some kind of sample app or even more usage examples for your supplied UIX components. Looking forward to get to know how to use PaginationViews properly.

**Comment by vmanot** [comment]
I'm currently in the process of improving the `PaginatedViews` API, documentation and fixes should be coming soon :)

**Comment by emma-k-alexandra** [comment]
Also struggling with `PaginatedViews` and could use some guidance.

**Comment by vmanot** [comment]
@michaelkroll  @emma-k-alexandra documentation is up [here](https://github.com/SwiftUIX/SwiftUIX/wiki/Pagination). Please feel free to email/iMessage me if you have any further questions.
