### ISSUE TITLE
Setting font for TextView doesn't work

### ISSUE THREAD

**Issue by jchitel** [SwiftUIX/SwiftUIX#132]
When you try to set the font for a `TextView` (either via `.font()` or `.environment(\.font, font)`), it still uses the default font.

I placed a breakpoint on [this line](https://github.com/SwiftUIX/SwiftUIX/blob/aee925b7f4b6a29cfb7985f32d411022176b53b3/Sources/Intramodular/Text/TextView.swift#L158) (where the environment font is applied to the `UITextView`), and it doesn't get hit. This means that in my code, `updateUIView()` does not seem to be called.

I believe that the simple fix for this is to include the `updateUIView()` logic in the `makeUIView()` method.

**Comment by vmanot** [comment]
@jchitel which version of iOS are you targeting?

**Comment by jchitel** [comment]
iOS 13+ but I observed this in the iOS 14 emulator.

**Comment by vmanot** [comment]
@jchitel fixed.
