### ISSUE TITLE
Add alwaysBounce to CocoaScrollView

### ISSUE THREAD

**Issue by PKizzle** [SwiftUIX/SwiftUIX#136]
Even though the CocoaScrollViewConfiguration supports it there is no ViewModifier available to change the alwaysBounceHorizontal or alwaysBounceVertical property.
This is especially helpful in combination with the `onRefresh` functionality.

```
public func alwaysBounceVertical(_ enabled: Bool) -> Self {
        then({ $0.configuration.alwaysBounceVertical = enabled })
}

public func alwaysBounceHorizontal(_ enabled: Bool) -> Self {
        then({ $0.configuration.alwaysBounceHorizontal = enabled })
}
```

**Comment by vmanot** [comment]
@PKizzle good catch, thanks!
