### ISSUE TITLE
.keyboardAvoiding()

### ISSUE THREAD

**Issue by writing-shed** [SwiftUIX/SwiftUIX#137]
I have been using .keyboardAvoiding() which I thought was part of SwiftUIX. If it was then it has gone. Am I correct?

**Comment by vmanot** [comment]
@writing-shed it's now been renaming to `.padding(.keyboard)`, to better reflect the nature of its implementation.

**Comment by writing-shed** [comment]
<rant> To be successful an API depends heavily on the quality of its documentation. SwiftUIX contains lots of good stuff, but the documentation is almost non existent. Perhaps that is intentional, but I doubt it. More likely it is lack of time. Saying this I wonder what Apple's excuse is for the lamentable state of SwiftUI documentation. </rant>

**Comment by vmanot** [comment]
@writing-shed it's due to a lack of time, unfortunately. I am looking up to ramp up documentation and reach a stable 1.0 version soon, but it will take a bit more time. I apologize for any unforeseen breakage in your projects.
