### ISSUE TITLE
Autohide keyboard when tap outside TextField

### ISSUE THREAD

**Issue by GJNilsen** [SwiftUIX/SwiftUIX#14]
When tapping outside the TextField, the keyboard should hide automatically.

**Comment by vmanot** [comment]
@GJNilsen please take a look at `Keyboard.dismiss()`. You can invoke it via a `View.tapGesture` on your background view.

**Comment by GJNilsen** [comment]
This is not possible when you are working with a list view. If you add gestures on the background all  links, pickers and so on will stop working.
