### ISSUE TITLE
Localizing placeholder

### ISSUE THREAD

**Issue by vmshaneeb** [SwiftUIX/SwiftUIX#141]
Localizing of place holder strings is not working in SwiftUI..

I tried this..

`SearchBar(text: $searchTxt)
                .placeholder(String.localizedStringWithFormat(NSLocalizedString("Search", comment: "Search")))`

if I put 

`SearchBar(text: $searchTxt)
                .placeholder(LocalizedStringKey("Search")))`

I get "cannot convert value of type 'LocalizedStringKey' to expected argument type 'String'"

**Comment by vmanot** [comment]
@vmshaneeb unfortunately, `LocalizedStringKey` is opaque to 3rd party developers and cannot be converted to a `String`. You'll have to resort to manual localization for now. I'd love to extend both `CocoaTextField` and `SearchBar` to support it fully, but there's no public API for me to consume here :(
