### ISSUE TITLE
Split into modules

### ISSUE THREAD

**Issue by jondwillis** [SwiftUIX/SwiftUIX#142]
It would be amazing if this library was split into modules, so developers could choose which features they want, while keeping the app size impact lower.

**Comment by vmanot** [comment]
@jondwillis I'm open to suggestions - I do understand that the project has grown considerably. Unfortunately, I don't have the time at the moment to split it up. Please contact me at vatsal.manot@yahoo.com (iMessage/Mail) if you do have concrete ideas on how to push this further, but I'm closing this ticket for now.
