### ISSUE TITLE
CocoaTextField crashes with placeholder

### ISSUE THREAD

**Issue by jcrate** [SwiftUIX/SwiftUIX#144]
CocoaTextField crashes on iOS 14 (Simulator) and iOS 13 (iPhone 11, 13.7) when using a placeholder. 

I'm not sure if it's related, but the label never displays. I didn't want a label so this doesn't matter.

I copied the CocoaTextField file to use in my project with a formatter, and to use a placeholder, I just changed this block of code to set the `uiView.placeholder` instead of the `uiView.attributedPlaceholder`. I am not specifying a font for the CocoaTextField.

```
        if let placeholder = placeholder {
            uiView.attributedPlaceholder = NSAttributedString(
                string: placeholder,
                attributes: [
                    .font: font as Any,
                    .paragraphStyle: NSMutableParagraphStyle().then {
                        $0.alignment = .init(multilineTextAlignment)
                    }
                ]
            )
        } else {
            uiView.attributedPlaceholder = nil
            uiView.placeholder = nil
        }
```
 to
```
        if let placeholder = placeholder {
            uiView.placeholder = placeholder
        } else {
            uiView.attributedPlaceholder = nil
            uiView.placeholder = nil
        }

```
and I commented this extension func because I wasn't sure if this one was being called and setting a label.
```
    public func placeholder(_ placeholder: String) -> Self {
        then {
            $0.label = Text(placeholder).kerning(kerning)
            $0.placeholder = placeholder
        }
    }
```

On a side note, it was easy to add optional formatter support using https://github.com/luximetr/AnyFormatKit. I don't know if there's a policy about integrating with other packages, or whether this integration could be done in a way that makes AnyFormatKit an optional dependency. It looks like `#if canImport(AnyFormatKit)` might support this? I could submit a PR if this is a direction you'd like to explore.

**Comment by vmanot** [comment]
@jcrate what's the crash log?

**Comment by vmanot** [comment]
@jcrate nvm, figured out what the issue was. `font` is a SwiftUI `Font`, and I accidentally forgot to add the `.toUIFont()` conversion before passing it to `NSAttributedString`. It should be fixed now, thank you for your patience :)
