### ISSUE TITLE
PaginationView: PageControl not visible on bright backgrounds

### ISSUE THREAD

**Issue by mlinzner** [SwiftUIX/SwiftUIX#145]
PageControl on bright background is not visible:
![Light Mode](https://user-images.githubusercontent.com/7240176/95070503-7fc9da80-0708-11eb-8660-95bc5a6e7771.png)

Same view in dark mode:
![Dark Mode](https://user-images.githubusercontent.com/7240176/95070542-8bb59c80-0708-11eb-9c62-5cb1e46a8a99.png)

I've worked around it by modifying `pageIndicatorTintColor` and `currentPageIndicatorTintColor` in the environment, but I think it would be nice to have access to the UIPageView / UIPageViewController background to be able to get something more similar to the system style. E.g.:
![Goal](https://user-images.githubusercontent.com/7240176/95070852-0383c700-0709-11eb-8233-71e2d143496a.png)

**Comment by vmanot** [comment]
@mlinzner is there a way to enable the system background programmatically, by modifying either `UIPageViewController` or `UIPageControl`? Because I could expose that as a view modifier.

**Comment by mlinzner** [comment]
Yes, UIPageControl inherits `backgroundColor` from UIView and it works similar to the indicator tint colors:

```swift
view.backgroundColor = UIColor(white: 0.0, alpha: 0.3)
```

<img width="166" alt="Screen Shot 2020-10-06 at 9 29 14 AM" src="https://user-images.githubusercontent.com/7240176/95171596-6c754880-07b6-11eb-873f-d4e83a665e06.png">

iOS 14 in addition added [`backgroundStyle`](https://developer.apple.com/documentation/uikit/uipagecontrol/backgroundstyle) to `UIPageControl`

```
case automatic
    The default background style, which adapts in response to changes in the page control’s interaction state.

case prominent
    The background style that shows a full background regardless of the interaction.

case minimal
    The background style that shows a minimal background regardless of the interaction.
```

**Comment by vmanot** [comment]
@mlinzner pull in the latest master and use `View.pageControlBackgroundStyle(_:)` to set the background style for the page control.

**Comment by mlinzner** [comment]
Amazing, thanks!

**Comment by vmanot** [comment]
@mlinzner you're welcome! :)
