### ISSUE TITLE
PaginationView: Dynamic content no longer working?

### ISSUE THREAD

**Issue by mlinzner** [SwiftUIX/SwiftUIX#147]
Dynamic content loading (https://github.com/SwiftUIX/SwiftUIX/issues/50) doesn't seem to work anymore.

* Deploy Target iOS 14
* Xcode 12.0.1 (12A7300)
* SwiftUIX on master (0cee3386e843ebd3e442d5e6afa028356e28c539)

Plain Test Project with one view:

```swift
struct ContentView: View {
    var body: some View {
        PaginationView {
            ForEach([1, 2, 3], id: \.hashValue) {
                Text(String($0))
            }
        }
    }
}
```
Result:
![Simulator Screen Shot - iOS 14 - 2020-10-16 at 11 00 05](https://user-images.githubusercontent.com/7240176/96238948-5712d200-0f9f-11eb-9155-00a25706383b.png)

While 
```swift
struct ContentView: View {
    var body: some View {
        PaginationView {
            Text("1")
            Text("2")
            Text("3")
        }
    }
}
```
works as expected.

I would assume that initializer
```swift
    public init<Data, ID>(
        axis: Axis = .horizontal,
        transitionStyle: UIPageViewController.TransitionStyle = .scroll,
        showsIndicators: Bool = true,
        content: () -> ForEach<Data, ID, Page>
    )
```
will be called, but as far as I can see it's not. Instead the ArrayBuilder initializer is called:
```swift
    public init(
        axis: Axis = .horizontal,
        transitionStyle: UIPageViewController.TransitionStyle = .scroll,
        showsIndicators: Bool = true,
        @ArrayBuilder<Page> content: () -> [Page]
    ) 
```

which produces a pages array of count 1:
<img width="289" alt="2020-10-16 at 10 26 23" src="https://user-images.githubusercontent.com/7240176/96239084-8aedf780-0f9f-11eb-8127-4c69cb92e589.png">

**Comment by vmanot** [comment]
@mlinzner fixed - had to sprinkle in `@_disfavoredOverload` to improve overload resolution. SwiftUI confuses the compiler a lot.
