### ISSUE TITLE
UniformTypeIdentifiers unavailable in MacCatalyst

### ISSUE THREAD

**Issue by easiwriter** [SwiftUIX/SwiftUIX#148]
I'm getting a compilation error in FileImportLink.swift when compiling a universal app. It says UniformTypeIdentifiers is not available when building for Mac Catalyst. This started happening on move to Xcode 12

**Comment by vmanot** [comment]
Can you try the 0.0.3 branch?

**Comment by easiwriter** [comment]
That’s fixed it thanks

**Comment by Overcot** [comment]
This issue still exist in file DocumentPicker.swift
Commit hash 2b461698d3eaf51cdad1a85f1e920e1a705ce2d3
