### ISSUE TITLE
Navigator always nil

### ISSUE THREAD

**Issue by mistralaix** [SwiftUIX/SwiftUIX#150]
Hi,

I would like to use Navigator in my project.
The problem is that the navigator environment variable is always nil. It's working great for presenter but I don't understand why navigator is not working.

## What did I do:
I embedded my first view like that:
``` swift
CocoaHostingController(rootView: CustomNavigationView { contentView } )
```

In my contentiew, I am getting the environment value:
``` swift
@Environment(\.navigator) var navigator
```

When the user clicks on a button, I am doing the following action:
``` swift
self.navigator!.push(LoginView())
```
--> I am getting an exception because navigator is nil

Thank you all for your help!

**Comment by vmanot** [comment]
Hmm, can you wrap `contentView` in a `PresentationView` and see if that fixes your issue? Also, are you sure you're on the latest master?

**Comment by vmanot** [comment]
@mistralaix oh nevermind, this is fixed! Please update to the latest `master`. Didn't realize `CustomNavigationView` was from this module itself lol
