### ISSUE TITLE
Samples for CollectionView and List

### ISSUE THREAD

**Issue by alexyak** [SwiftUIX/SwiftUIX#152]
Where can find sample for how to use your CollectionView and List?

**Comment by vmanot** [comment]
@alexyak These are being majorly reworked, I'll add documentation when the rework is complete.

**Comment by vmanot** [comment]
The `CollectionView` refactor is nearly complete, the internal implementation has now completely been swapped out to use diffable data sources. Examples and docs will come up very soon (in the next week or so).

**Comment by vmanot** [comment]
`CollectionView` is still under major rework, and `CocoaList` will likely be deprecated. I have docs in mind, am waiting for the APIs and performance to stabilize. Closing this for now.

**Comment by jbromberg** [comment]
Still not seeing any docs for CollectionView. Is this coming?
