### ISSUE TITLE
AppActivityView terminates App on iPad

### ISSUE THREAD

**Issue by JulianKahnert** [SwiftUIX/SwiftUIX#154]
When using `AppActivityView` on an iPad, the App terminates with this exception:
```
Terminating app due to uncaught exception 'NSGenericException', reason: 'UIActivityViewController can only be used modally or as contentViewController in popover on iPad.'
```

**Comment by vmanot** [comment]
@JulianKahnert as a workaround, use `UserInterfaceIdiom` to check whether it's running on an iPhone or an iPad - and present as a popover on iPad.
