### ISSUE TITLE
NavigationBarItems(leading and trailing) not showing in modals when the center one is set

### ISSUE THREAD

**Issue by mistralaix** [SwiftUIX/SwiftUIX#156]
Hi,

I would like to use a navigationBarItems in a modal.
When an item is set at the center, the leading and trailing views are not shown. If I remove the center one, leading and trailing items are shown.

#What did I do?
I am presenting my view like that:
``` swift
self.presenter!.present(CustomNavigationView { MyView() })
```

In MyView:
``` swift
VStack(alignment: .center) {
    Text("First screen")
    .navigationBarItems(leading: Text("A text"), center: Text("Title"), trailing: Button("Dismiss", action: {}), displayMode: .inline)
}
```

Thank you all for your help!

**Comment by vmanot** [comment]
@mistralaix fixed this, please pull in the latest `master`.
