### ISSUE TITLE
ImagePicker example

### ISSUE THREAD

**Issue by smaldd14** [SwiftUIX/SwiftUIX#158]
Does anyone have an example of them using SwiftUIX's ImagePicker?

**Comment by jevonmao** [comment]
I would love to help with adding an example into the documentation or whatever, how do I get started? I am new to this repository

**Comment by smaldd14** [comment]
@jevonmao I believe if you reply to this feed and tag @vmanot , he may be able to add it to his documentation.

**Comment by vmanot** [comment]
@jevonmao please just create a Markdown file anywhere and open a PR, I can copy and paste the contents to the wiki. GitHub Wikis don't support collaboration currently (which is crazy in 2020), hence the awkward process.

Apologies for the delayed reply to this issue - am strangled with work at the moment. @smaldd14, you'd use `ImagePicker` within a `View.sheet` or a `View.popover` - just like any other view. It takes a `Binding<Data>` and allows you to specify the encoding of the image you want. Image mutli-select support will be added soon, but feel free to open a PR for it if needed.
