### ISSUE TITLE
Performance for single source truth pattern state manangement

### ISSUE THREAD

**Issue by jackyccaa** [SwiftUIX/SwiftUIX#159]
This is not a bug report but kind of feature request.

SwiftUI&Combine is a big game change especially Redux-like single source truth state management. I can see a couple of framework like https://github.com/ReSwift/ReSwift.

However, all of those frameworks come a problem: scale performance. For example below, any change in `store` brings whole view rendering even I don't use that sub-state which is changing.
```swift
struct MyView: View {

  @ObservedObject var store: Store

  var body: some View {
    NavigationView {
      ...
    }
  }
}
```

Is there a way to provide a util ( slice/derived store) similar like [this](https://vergegroup.github.io/Verge/docs/VergeStore/optimization-tips)?

**Comment by vmanot** [comment]
@jackyccaa I have a framework used in a couple of production apps offering the granularity you're looking for - it's called [Reactor](https://github.com/vmanot/Reactor). I'll be adding documentation soon.
