### ISSUE TITLE
TextView Placeholder not dissappearing anymore

### ISSUE THREAD

**Issue by GJNilsen** [SwiftUIX/SwiftUIX#16]
The TextView Placeholder text is not disappearing anymore when entering text in the field.
![IMG_0489](https://user-images.githubusercontent.com/628887/70380306-33234080-1939-11ea-9f49-0c3a806e8162.jpg)

**Comment by vmanot** [comment]
@GJNilsen this should be fixed now.

**Comment by qizh** [comment]
I still have this issue. Xcode 11.3, iOS 13.3.

**Comment by qizh** [comment]
I still have this issue. Xcode 11.3, iOS 13.3.
