### ISSUE TITLE
It is great, but CocoaTextField not support Chinese and Japanese.

### ISSUE THREAD

**Issue by gliese667c** [SwiftUIX/SwiftUIX#160]
**Describe the bug**
It is great, but not support Chinese and Japanese.

**To Reproduce**

Just add a Chinese or Japanese keyboard then switch to it, type any words in CocoaTextField, the first word is correct, type one suggestion word, then type any words always are English.

**Comment by vmanot** [comment]
@gliese667c this has been reported before - I'm really not sure what's causing the problem. Could you copy `CocoaTextField`'s implementation and play around with it?

**Comment by gliese667c** [comment]
I don't know what the problem is, it' s very weird.

**Comment by mvarie** [comment]
There's an interesting discussion here:

https://github.com/ReactiveX/RxSwift/issues/649

.. it's about RxSwift, not SwiftUI, but it seems rather relevant - as it applies to languages that have multistage text input (such as Chinese and Japanese), and two-way binding.

Note, especially, their fix:

https://github.com/ReactiveX/RxSwift/issues/649#issuecomment-215983367

```
/**
    Reactive wrapper for `text` property. Notifications are fired only when when there
    isn't any marked text.
    */
    public var rx_nonMarkedText: ControlProperty<String> {
        let textProperty = self.rx_text
        return ControlProperty(
            values: textProperty._values.filter { [weak self] _ in self?.markedTextRange == nil },
            valueSink: textProperty._valueSink
        )
    }

```

I have no familiarity with these languages and with multistage text editing, however it seems that, while the UITextView has undetermined text (with `markedTextRange` != nil), you should not fire a notification (update the binding property).

I may be barking up the wrong tree – again, no familiarity with this issue and the languages mentioned.

**Comment by vmanot** [comment]
@mvarie I'll take a look, thank you!

**Comment by stevema** [comment]
> @mvarie I'll take a look, thank you!

I have the same issue.

**Comment by vmanot** [comment]
@gliese667c @mvarie @stevema this has now been fixed! Thank you for your patience.

**Comment by n41l** [comment]
This issue still remains in TextView component.  Add `guard textView.markedTextRange == nil, text?.wrappedValue != textView.text else { return }` in `textViewDidChange(_ textView: UITextView)` function can fix this too.

**Comment by gliese667c** [comment]
这是来自邮箱的自动回复。来信已收到，我会尽快回复给您。

**Comment by vulgur** [comment]
@n41l @vmanot Yes, the bug still remains in 0.1.2, plz reopen the issue.


> This issue still remains in TextView component. Add `guard textView.markedTextRange == nil, text?.wrappedValue != textView.text else { return }` in `textViewDidChange(_ textView: UITextView)` function can fix this too.

**Comment by gliese667c** [comment]
这是来自邮箱的自动回复。来信已收到，我会尽快回复给您。
