### ISSUE TITLE
CocoaTextField does not respect .font()

### ISSUE THREAD

**Issue by lewis-smith** [SwiftUIX/SwiftUIX#161]
Thanks for a great library! I found a small bug. I'm just going to use un-styled text in project, but I thought you might want to know.

    import SwiftUIX

    struct NoFontView: View {
        
        @State var title = "Hello world!"
        
        var body: some View {
            VStack {
                CocoaTextField("Title", text: $title)
                    .isFirstResponder(true)
                    .font(.system(size: 24, weight: .black))
                
                TextField("Title", text: $title)
                    .font(.system(size: 24, weight: .black))
            }
        }
    }

    struct CocoaTextField_Previews: PreviewProvider {
        static var previews: some View {
            NoFontView()
        }
    }

Results in the following output: 

<img width="199" alt="CleanShot 2020-11-07 at 15 20 06@2x" src="https://user-images.githubusercontent.com/1905433/98444949-bd0cf800-210c-11eb-93e1-1f0b48901e25.png">

This is tested agains v0.0.3

**Comment by vmanot** [comment]
Yeah, unfortunately SwiftUI exposes no way to convert a `Font` to a `UIFont`. So I end up depending on a fragile, runtime reflection based approach. `CocoaTextField` supports a `.font(_:UIFont)` modifier though, so if you pass in a `UIFont` it should work alright.
