### ISSUE TITLE
KeyboardAvoidance improvement

### ISSUE THREAD

**Issue by RobertKoval** [SwiftUIX/SwiftUIX#165]
Please, add public API for **isSystemEnabled** property in **KeyboardAvoidance** modifier. I need to move my View inside ZStack, which also has nested VStack with `.ignoresSafeArea(.keyboard, edges: .bottom) ` modifier. As the result, padding doesn't work when keyboard appears.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/22445842/98712331-d624db80-238e-11eb-84ad-5c5f8578a408.png">

**Comment by vmanot** [comment]
@RobertKoval I believe you can do this currently:

```foo.padding(isPaddingEnabled ? .keyboard : nil``` 

Where `isPaddingEnabled` is a `Bool` defined by you. Hope that fixes your issue :)

**Comment by vmanot** [comment]
@RobertKoval pull in the latest master, then use `.padding(.keyboardForced)`.

**Comment by RobertKoval** [comment]
Just tested on iOS 14,
problem in: `padding = keyboardHeight > 0 ? keyboardHeight - geometry.safeAreaInsets.bottom : 0`,
`keyboardHeight == 336.0` and  `geometry.safeAreaInsets.bottom == 336.0`, as a result **padding** is _0_ and it does nothing :(

**Comment by vmanot** [comment]
@RobertKoval good catch, fixed.
