### ISSUE TITLE
东西很好，但是文档不够健全。

### ISSUE THREAD

**Issue by damonZDM** [SwiftUIX/SwiftUIX#166]
文档中介绍的东西过于表面，没有更多的示例和用法。使用起来有些困难

**Comment by jevonmao** [comment]
观察的很好，这个Repo其实还需要很多的完善，但是有潜力。能具体举些不完善的例子吗？什么功能的文档需要完善？
（P.S. 为啥用中文开issue啊？这边外国人应该看不懂吧)

**Comment by vmanot** [comment]
As I understand it, this issue pertains to the state of documentation. It's actively being worked upon - I'm just extremely caught up with work at the moment.
