### ISSUE TITLE
Cannot find CocoaTextField in scope.

### ISSUE THREAD

**Issue by MarkLyck** [SwiftUIX/SwiftUIX#168]
Tried installing SwiftUIX to use `CocoaTextField` firstResponder since that's still missing from SwiftUI.

However I can't seem to get the package to work :(

I get the following error when trying to build:

<img width="922" alt="Screen Shot 2020-11-19 at 09 02 08" src="https://user-images.githubusercontent.com/6841110/99675992-e8b1ab80-2a45-11eb-86e7-6b94b6c3cca9.png">

I added the package following the installation instructions:
<img width="1183" alt="Screen Shot 2020-11-19 at 09 02 39" src="https://user-images.githubusercontent.com/6841110/99676036-fb2be500-2a45-11eb-9df9-1bfa4f41e9f1.png">

However I was not able to find anything called "Linked Frameworks and Libraries" in the project settings for Xcode 12.2

It is however in this section, which I assume replaces the old "Linked Frameworks and Libraries"?

<img width="964" alt="Screen Shot 2020-11-19 at 09 04 08" src="https://user-images.githubusercontent.com/6841110/99676195-30383780-2a46-11eb-8c1d-f0e2984634f8.png">

I tried to close Xcode and start it back up, and I tried to clean the build folder with no luck. Any idea why this isn't working?

Xcode: Version 12.2 (12B45b)

**Comment by Overcot** [comment]
show your full file please. Did you write import SwiftUIX before declaring view?

**Comment by jevonmao** [comment]
on top of your file, write `import SwiftUIX`

**Comment by vmanot** [comment]
As others have noted, please import the SwiftUIX module.
