### ISSUE TITLE
CocoaTextField lacks font modifier support

### ISSUE THREAD

**Issue by kolyafabrika** [SwiftUIX/SwiftUIX#169]
Hi and thank you for great work.

Currently, CocoaTextField seems to work just fine with font modifiers like .font(.largetitle) but as soon as I ask it to change the weight or design, it seems to ignore it.

**This won't work:**
.font(.system(size: 130, weight: .bold, design: .rounded))

**Comment by Overcot** [comment]
I can't reproduce this. I created Example code to change font size with slider

```swift
struct ContentView: View {
    @State var text: String = ""
    @State var value: Double = 10.0
    var body: some View {
        VStack {
            CocoaTextField("Test", text: $text).font(.system(size: CGFloat(value), weight: .bold, design: .rounded))
            Slider(value: $value, in: 10...100)
        }
    }
}

Maybe you can show some code to reproduce this?

```

> Hi and thank you for great work.
> 
> Currently, CocoaTextField seems to work just fine with font modifiers like .font(.largetitle) but as soon as I ask it to change the weight or design, it seems to ignore it.
> 
> **This won't work:**
> .font(.system(size: 130, weight: .bold, design: .rounded))

**Comment by jevonmao** [comment]
I tested with your exact line `.font(.system(size: 130, weight: .bold, design: .rounded))` and it works.

**Comment by kolyafabrika** [comment]
Hi, for me it works until I start typing. Here's my code:

`import SwiftUI
import SwiftUIX

struct ContentView: View {
    @State var text: String = ""
    var body: some View {
        VStack {
            CocoaTextField("CocoaTextField", text: $text)
                .font(.system(size: 36, weight: .heavy, design: .rounded))
            TextField("TextField", text: $text)
                .font(.system(size: 36, weight: .heavy, design: .rounded))
        }
    }
}
`

**Comment by vmanot** [comment]
This is due to the fact that SwiftUIX relies on a naive `Font` → `UIFont` conversion. To pass a UIKit directly - pass a `UIFont` like so:

```myTextField(UIFont.xxx)```

**Comment by saltwat5r** [comment]
Hi, I have the same problem. CocoaTextField is not working with .font() modifier at all.
