### ISSUE TITLE
add animated parameters to the push, pop and poptoroot methods of navigator？

### ISSUE THREAD

**Issue by damonZDM** [SwiftUIX/SwiftUIX#175]
英文不是太好，大概意思就是希望能给Navigator的push、pop、popToRoot方法增加animated参数。
We hope to add animated parameters to the push, pop and poptoroot methods of navigator.

**Comment by vmanot** [comment]
@damonZDM done. Use `push(foo, withAnimation: nil)` and `pop(withAnimation: nil)`.
