### ISSUE TITLE
CocoaTextField.isFirstResponder(true) causes the keyboard to show when Alert is shown

### ISSUE THREAD

**Issue by mnabokow** [SwiftUIX/SwiftUIX#179]

**Comment by vmanot** [comment]
@mnabokow I updated `CocoaTextField` to prevent becoming the first responder if `.disabled(true)` is attached to it. 

Simply use `.disabled(isMyAlertShowing)` to fix the issue.

**Comment by mnabokow** [comment]
That works perfectly, thanks @vmanot!
