### ISSUE TITLE
ImagePicker first Image always rotated 180 degrees

### ISSUE THREAD

**Issue by hannesharnisch** [SwiftUIX/SwiftUIX#181]
When I run a simple test app with the ImagePicker in a sheet toggled by a simple button, when I select the first Image in the ImagePicker the Image gets rotated 180 degrees when I present it. This doesn't happen with any other images I select.

https://user-images.githubusercontent.com/26021359/102988490-438e6500-4514-11eb-9db0-ee5379257743.mov

**Comment by vmanot** [comment]
@hannesharnisch super weird - is this a UIKit bug as well?

**Comment by hannesharnisch** [comment]
I don’t think so. I implemented the Imagepicker for SwiftUI without swiftuix as well, at least with editing on and it always worked.

**Comment by Phzytaylor** [comment]
I think this has been a common problem when using pngs instead of jpegs. I noticed when uploading png data to firebase it always rotates the image 180 degrees. I bet if you switch to jpeg it won't rotate.

**Comment by abadikaka** [comment]
ur assumption maybe correct @Phzytaylor, but those images are derived from apple system in simulator, I don't think they have different format for each sample picture provided by them. interesting issue
