### ISSUE TITLE
Adding font weight modifier breaks CocoaTextField font size

### ISSUE THREAD

**Issue by mnabokow** [SwiftUIX/SwiftUIX#183]
<img width="293" alt="CleanShot 2020-12-31 at 18 53 28@2x" src="https://user-images.githubusercontent.com/45775419/103420886-cd37d580-4b99-11eb-891e-f00790b98480.png">
<img width="304" alt="CleanShot 2020-12-31 at 18 58 27@2x" src="https://user-images.githubusercontent.com/45775419/103420967-3ae40180-4b9a-11eb-8bc5-bbca52405bdb.png">

This happens with **both** font weight modifier options below.

1.
```
CocoaTextField("username", text: $username)
            .font(Font.title.weight(.bold))
```

2.
```
CocoaTextField("username", text: $username)
              .font(.title, weight: .bold)
```

**Comment by vmanot** [comment]
@mnabokow unfortunately `CocoaTextField` cannot perform a complete `SwiftUI.Font` → `UIKit.UIFont` conversion yet (due to limitations in the SwiftUI API itself). Try passing a `UIFont` via the `CocoaTextField.font(_:)` modifier.
