### ISSUE TITLE
CocoaTextField Crashes on iOS

### ISSUE THREAD

**Issue by bensinc** [SwiftUIX/SwiftUIX#185]
It's possible I'm missing something here, but trying to use CocoaTextField on iOS results in:

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<SwiftUIX.UIHostingTextField 0x7fa1414309e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key focusRingType.'

I've made it work by removing "uiView._focusRingType = configuration.focusRingType" from CocoaTextField.swift.

It seems that focusRingType is a MacOS feature, so I wasn't sure if CocoaTextField isn't intended for use on iOS, or if this is a bug. I could surround the focusRingType code with a check for MacOS and submit a pull request if that makes sense.

Thanks!

**Comment by damonZDM** [comment]
我也遇到了一样的问题，应该是私有API的属性名变了

**Comment by vmanot** [comment]
@bensinc @damonZDM fixed. Please update to the [0.0.5 release](@bensinc @damonZDM fixed. Please update to the 0.0.5 tag - https://github.com/SwiftUIX/SwiftUIX/releases/tag/0.0.5.).
