### ISSUE TITLE
How to change automaticallyShowSearchBar value

### ISSUE THREAD

**Issue by mrsunx** [SwiftUIX/SwiftUIX#187]
Hello, can you tell me how to change automaticallyShowSearchBar value

thank you

```swift
Text("Hello, world!")
    .navigationSearchBar {
        SearchBar("Placeholder", text: $text)
    }
```

**Comment by vmanot** [comment]
@mrsunx this is currently left unexposed due to a bug in `NavigationView` (`automaticallyShowSearchBar` doesn't work as expected) in iOS 14.
