### ISSUE TITLE
TextView modifiers don't work as expected

### ISSUE THREAD

**Issue by DominikButz** [SwiftUIX/SwiftUIX#19]
Hi, great library but TextView doesn't work as expected. It seems onCommit is never executed.
The modifier font seems to work but foreground color, keyboard type and line limit don't seem to work either. I don't know how the keyboard can resign either. 
Thanks for looking int this. 

        TextView("Notes", text: self.$workoutManager.workout.notes, onCommit: {
            /// is never executed. 
             UIApplication.shared.windows[0].endEditing(true)
            
        }).font(.footnote).foregroundColor(.blue).keyboardType(.decimalPad).lineLimit(4)

**Comment by vmanot** [comment]
Thank you for raising this issue, I'll take a look! :)

**Comment by vmanot** [comment]
@DominikButz could you take a look at `CocoaTextField`? I ran into similar problems while designing that and realized I'd have to manually implement those modifiers and their associated APIs as `EnvironmentValues` doesn't expose `foregroundColor` nor `keyboardType`.

Moreover, `Font` → `UIFont` right now is implemented via a hack, as there is no official API that offers a conversion from SwiftUI → AppKit/UIKit. I've filed multiple radars for this with no luck thus far.
