### ISSUE TITLE
Overriding `hidesSearchBarWhenScrolling`

### ISSUE THREAD

**Issue by sejr** [SwiftUIX/SwiftUIX#190]
Hi there,

I'm hoping to override this property to always display the search bar on a specific navigation view item: https://github.com/SwiftUIX/SwiftUIX/blob/e45ba961455add7793ab6411d0fe8bc66d255f9a/Sources/Intramodular/Search/SearchBar%2BNavigationView.swift#L19

I'm not entirely sure of the correct way to do this. I'd think that any view that is able to define its own search bar would be able to provide an additional modifier.

```swift
struct MySearchableListView: View {
    var body: some View {
        NavigationView {
            List {
                // list items...
            }
            .navigationSearchBar {
                SearchBar("Search Companies", text: $searchText)
            }
            .hidesSearchBarWhenScrolling(false)
        }
    }
}
```

**Comment by vmanot** [comment]
Take a look at `View/navigationSearchBarHiddenWhenScrolling(_:)` (also documented in the README).

**Comment by sejr** [comment]
@vmanot works like a charm. You rock.
