### ISSUE TITLE
PaginationView doesn't show

### ISSUE THREAD

**Issue by DominikButz** [SwiftUIX/SwiftUIX#20]
Hi,
 it seems that PaginationView doesn't show in the main view where I place it. See a couple of examples of what I tried below.

    ScrollView(.vertical) {
            
                VStack(alignment: .leading) {

                    ExerciseMediaPaginatedHeader(exercise: self.exercise)
                

                    .... other views
}
}

This doesn't show inside the Scroll view above:

struct ExerciseMediaPaginatedHeader: View {
    
    let exercise:Exercise
      
      var body: some View {
        PaginationView(axis: Axis.horizontal) {

            Text("bla")
            Text("blup")
            Text("foo")
        }
      }
}

Pagination view also does not show in the scroll view above if I add more complex views: 

struct ExerciseMediaPaginatedHeader: View {
    
    let exercise:Exercise
      
      var body: some View {
        PaginationView(axis: Axis.horizontal) {
            
            self.getViews()
        }
      }
    
    func getViews()->[AnyView] {
        
        var views: [AnyView] = [VideoZStackView(storagePath: self.exercise.videoStoragePath).eraseToAnyView()]
        self.exercise.imageStoragePaths.forEach { (path) in
            let firebaseImageView = FirebaseImage(storagePath: path).frame(width: CGFloat(UIScreen.main.bounds.width  - CGFloat(20)), height: CGFloat(UIScreen.main.bounds.width - 20) / CGFloat(1.78), alignment: .center).aspectRatio(contentMode: .fill).eraseToAnyView()
            views.append(firebaseImageView)
        }
        return views
    }
    
}

When adding more complex views without using the getViews func above , the swift compiler thows some BS SwiftUI-style fake errors that we all love:

      var body: some View {
        PaginationView(axis: Axis.horizontal) {
            
            VideoZStackView(storagePath: self.exercise.videoStoragePath).eraseToAnyView()

            FirebaseImage(storagePath: self.exercise.imageStoragePaths.first!).frame(width: CGFloat(UIScreen.main.bounds.width  - CGFloat(20)), height: CGFloat(UIScreen.main.bounds.width - CGFloat(20)) / CGFloat(1.78), alignment: .center).aspectRatio(contentMode: .fill).eraseToAnyView()

// 'fake' compiler error: "Binary operator / cannot be applied to types Int and Double" .  But I used this views within other views before and there was no error. 
        }
      }

thanks for looking into this.

regards
Dominik

**Comment by DominikButz** [comment]
update: it seems the PaginationView shows if I add a frame height: .frame(height: 350)... 
So it seems the PaginationView can't figure out its own height.

**Comment by vmanot** [comment]
@DominikButz huh, interesting. `PaginationView` internally uses an array of `UIHostingController`s, maybe I could query for `sizeThatFits` and use the max of all the pages as the frame.

**Comment by DominikButz** [comment]
thanks, maybe you can try that out and add it to a future update. It's ok, I can figure out the content height beforehand and simply set the height of the frame, it works for my use case.
