### ISSUE TITLE
PaginationView overlapping pages issues

### ISSUE THREAD

**Issue by transat** [SwiftUIX/SwiftUIX#204]
I've got a detail view consisting of a Pagination view with 3 pages. When my app's  navigationView's sidebar is expanded (on iPad in landscape mode) the detail view adapts itself (mostly elements shift t the right beyond the visible area. All of this is as expected! BUT if I paginate when in this sidebar-expanded state, the first page is shown overlapping the second (which itself overlaps the 3rd when I navigate to it). Any idea what could be happening?

**Comment by vmanot** [comment]
@transat would it be possible for you to reproduce this in a sample project and attach it here? Hard for me to tell based on your description currently.

**Comment by transat** [comment]
I haven't been able to reproduce this with a simple example, alas. It must be some edge-case to do with my specific implementation. I'll let you know if I figure out what's going on.

**Comment by vmanot** [comment]
@transat closing this issue for now, but please do reopen it if you can repro in an isolated case!

**Comment by okcoker** [comment]
@vmanot I'm running into an overlap issue with other views seemingly ending up underneath the PaginationView.

Here's a minimal project example. You'll notice it can take several clicks on the "Skip" button to recognize the tap

[paginationviewoverlap.zip](https://github.com/SwiftUIX/SwiftUIX/files/11283528/paginationviewoverlap.zip)
