### ISSUE TITLE
DynamicViewPresenter UIKit extensions break VIPER-based apps

### ISSUE THREAD

**Issue by Nickersoft** [SwiftUIX/SwiftUIX#205]
Great package @vmanot! I was eager to try it, but as my app is currently a VIPER-based UIKit that I'm slowly moving towards SwiftUI, there are still a number of VIPER modules in the codebase. In the VIPER architecture, most UIViewControllers already have a `presenter` class member, so I've been getting errors like this all across my codebase:

```
Overriding non-open property outside of its defining module
``` 

and

```
Property 'presenter' with type 'HomeSplitViewControllerPresenter?' cannot override a property with type 'DynamicViewPresenter?'
```

I realized it's due to this SwiftUIX extension:

https://github.com/SwiftUIX/SwiftUIX/blob/e4acefdd5b6e65574e8b251fd0ce7a89a624d707/Sources/Intramodular/Presentation/DynamicViewPresentable.swift#L19-L27

Surprisingly, all I did was add SwiftUIX to my SPM deps and this error started to crop up even in files where I wasn't importing SwiftUIX directly. Figured I would let you know. Happy to open a PR renaming this member to `viewPresenter` or something non-conflicting.

**Comment by vmanot** [comment]
@Nickersoft thank you for raising this issue! I'm planning on removing the public conformances completely and using some type erased wrapper for all my UIKit → SwiftUIX presenter needs. SwiftUIX ideally should not be publicly extending any UIKit symbols.

**Comment by vmanot** [comment]
Closing this for now because unfortunately I'm completely out of bandwidth. An exhaustive change is planned, but I cannot commit to any timeline right now due to a lack of time.
