### ISSUE TITLE
CocoaTextField onCommit() should be called in textFieldShouldReturn.

### ISSUE THREAD

**Issue by KlemenAndrasic** [SwiftUIX/SwiftUIX#211]
I think onCommit() should be called inside of the textFieldShouldReturn function instead of the textFieldDidEndEditing. Because resigning responder from the textField in any way triggers onCommit().

Example.:
Resigning firstResponder by user clicking in the empty space closes the popup with textField, but triggers onCommit as if user confirmed the text in the the textField.

**Comment by vmanot** [comment]
@KlemenAndrasic is this the behavior of the default SwiftUI `TextField`? I recall there being a similar issue a while ago. While I have no problem exposing a modifier such as `CocoaTextField/onReturn(perform:)`, I want to keep the behavior as close to Apple's API as possible.

**Comment by KlemenAndrasic** [comment]
@vmanot Per my testing  `onCommit` doesn't trigger when the keyboard is dismissed and therefore responder resigned on the textfield on the SwiftUI `TextField`.

**Comment by vmanot** [comment]
@KlemenAndrasic then I'm voting to close this issue - because as I understand `CocoaTextField` matches the current `TextField` behavior. Please feel free to reopen if needed.
