### ISSUE TITLE
Issue with CollectionView and NavigationLink

### ISSUE THREAD

**Issue by netayamin** [SwiftUIX/SwiftUIX#212]
Using collectionView which is displaying an image and NavigationLink to move between views doesn't work - it shows black screen and won't load the image unless I remove the navgiationLink.

**Comment by vmanot** [comment]
Very interesting - would it be possible for you to create a sample project reproducing this bug?

**Comment by vmanot** [comment]
Closing the issue due to inactivity, feel free to reopen with a repro case! :) 

Also, multiple updates have been made to `CollectionView` since this bug was reported, would love to know whether the issue still even persists.
