### ISSUE TITLE
Cannot change searchBar font size

### ISSUE THREAD

**Issue by X901** [SwiftUIX/SwiftUIX#220]
Hi , 
I cannot change searchBar font size and also if I put placeholder , the placeholder text won't change !

**Comment by vmanot** [comment]
This should be fixed now, `SearchBar` has a `SearchBar.font(_:UIFont)` modifier.

**Comment by X901** [comment]
> This should be fixed now, `SearchBar` has a `SearchBar.font(_:UIFont)` modifier.

I cannot access it ! , also placeHolder won't change !

<img width="817" alt="Screen Shot 2021-03-22 at 12 08 17 PM" src="https://user-images.githubusercontent.com/16876982/111966140-a12c5080-8b07-11eb-8a99-902a55fcb25a.png">

**Comment by vmanot** [comment]
@X901 you need to update SwiftUIX to the latest version. It seems like this is using the default SwiftUI modifier. Try explicitly specifying `UIFont.xxx`? Also, can you create a sample repro for not being able to change the placeholder? The code updates it every time the view is updated.

**Comment by X901** [comment]
> @X901 you need to update SwiftUIX to the latest version. It seems like this is using the default SwiftUI modifier. Try explicitly specifying `UIFont.xxx`? Also, can you create a sample repro for not being able to change the placeholder? The code updates it every time the view is updated.

I did tap on update to latest packages on  SPM menu , but nothing change 

what it appear to me is Font SwiftUI modifier only

I see that you new commit in Master branch 
but SPM didn't see it
