### ISSUE TITLE
PersistentObject vs StateObject discrepancy

### ISSUE THREAD

**Issue by zntfdr** [SwiftUIX/SwiftUIX#227]
Hi!
I'm experimenting with `@PersistentObject` as a substitute of `@StateObject` (for iOS 13 compatibility), however I've found this discrepancy:
when navigating back from a view using `@PersistentObject`, I would expect for the `@PersistentObject` value to be destroyed, however this is not the case. Going back into that view will show the previous value (no reset).

This differs from SwiftUI's `@StateObject`, here's an example:

| `@StateObject` |  `@PersistentObject` |
| --- | --- |
| ![stateobj 2021-04-07 17_08_51](https://user-images.githubusercontent.com/5277837/113850220-6e9b7c80-97c4-11eb-9d73-cf0a665d935c.gif) | ![swiftuix 2021-04-07 17_09_20](https://user-images.githubusercontent.com/5277837/113850117-5592cb80-97c4-11eb-8ea3-77488d3a7dc0.gif) |

This difference might be intentional: in this case the issue can be ignored.

Here's the code to reproduce the example above (just replace `@PersistentObject` with `@StateObject` to test SwiftUI's behavior)

```swift
struct ContentView: View {
  var body: some View {
    NavigationView {
      VStack {
        NavigationLink("go to a", destination: MyView())
        NavigationLink("go to b", destination: MyView())
      }
    }
  }
}

class MyModel: ObservableObject {
  @Published var text: String = "hello"
}

struct MyView: View {
  @PersistentObject var model: MyModel = .init()

  var body: some View {
    VStack {
      Text(model.text)
      Button("change") {
        model.text = ["a", "b", "c"].randomElement()!
      }
    }
  }
}
```

Thank you!

**Comment by vmanot** [comment]
@zntfdr I think I'm going to keep this as expected behavior, I thought about this a bit and I realized that I'd actually want this behavior for optimization reasons. Closing this ticket for now, please feel free to reopen if you have any comments/discussion points :)
