### ISSUE TITLE
AppActivityView onComplete modifier seems incorrect

### ISSUE THREAD

**Issue by matthewrobb** [SwiftUIX/SwiftUIX#230]
https://github.com/SwiftUIX/SwiftUIX/blob/0d232a92649d5946838dad0d57d77c10e30c66a2/Sources/Intramodular/Activity/AppActivityView.swift#L64

It appears to be assigning the calling function to onComplete where it should be assigning the action argument?

**Comment by vmanot** [comment]
@matthewrobb great catch!
