### ISSUE TITLE
CocoaTextField cannot set tag to enable "tabbing" between fields.

### ISSUE THREAD

**Issue by miguellan** [SwiftUIX/SwiftUIX#233]
In CocoaTextField.swift:

```
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
            var nextField: UIView?
            
            if textField.tag != 0 {
                let nextTag = textField.tag + 1
                var parentView = textField.superview
                
                while nextField == nil && parentView != nil {
                    nextField = parentView?.viewWithTag(nextTag)
                    parentView = parentView?.superview
                }
            }
            
            if let nextField = nextField {
                nextField.becomeFirstResponder()
            } else {
                textField.resignFirstResponder()
            }
            
            configuration.onCommit()
            return true
        }
```
I see the above code, which indicates that you should be able to do something like:

```
VStack {
  CocoaTextField("", text: $outputBinding)
                      .tag(1)
  CocoaTextField("", text: $outputBinding2)
                      .tag(2)
}
```

And then when hitting the return button on the first field, the focus should automatically shift to the second field.  However, when I place a break-point at `if textField.tag != 0 {`, and then do a po textField.tag, it is always equal to 0.   So how are you supposed to set the tag, and make use of this convenient feature?

**Comment by miguellan** [comment]
FYI, for now I have pulled in commit b495f16828a720aea44d1577cb4261781f8cf1a7, so that I can use the functionality that was added and then subsequently removed.

```
CocoaTextField("", text: $text)
                .responderIndex(1)
CocoaTextField("", text: $text2)
                .responderIndex(2)
```

**Comment by vmanot** [comment]
@miguellan this is being generalized into a more general responder chain construct.

**Comment by miguellan** [comment]
Was this fixed/resolved?  What is the proper way to do it now?
