### ISSUE TITLE
CollectionView inside NavigationView

### ISSUE THREAD

**Issue by ILYA2606** [SwiftUIX/SwiftUIX#234]
**When `CollectionView` inside `NavigationView`, it is impossible to remove the UINavigationBar.**  

`.navigationBarHidden(true)` not working

Sample code:
```swift
import SwiftUI
import SwiftUIX

struct ContentView: View {
    var body: some View {
        NavigationView {
            VStack {
                Text("Title")
                CollectionView(0 ..< 1000, id: \.self) { number in
                    Text(String(number))
                }
            }
            .navigationBarHidden(true)
        }
    }
}
```

Preview:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/283493/114730499-98671d00-9d49-11eb-9d23-683577630c8b.png">

View Hierarchy:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/283493/114730410-838a8980-9d49-11eb-9ee8-0e12ee3adf29.png">

**Comment by bystritskiy** [comment]
+1

**Comment by joliejuly** [comment]
+1

**Comment by death654321** [comment]
+1

**Comment by vmanot** [comment]
@ILYA2606 @bystritskiy this is so bizarre... I'm not touching the nav controller nor the nav bar in any of my `UICollectionView` code :(

**Comment by vmanot** [comment]
Fixed, but use `View/hideNavigationBar()` instead of `navigationBarHidden(_:)`.
