### ISSUE TITLE
Document CocoaList & CollectionView

### ISSUE THREAD

**Issue by longbct** [SwiftUIX/SwiftUIX#238]
I am trying to use the CocoaList, but I could not find any working examples how to use it. Its would be great if we can provide some examples.

**Comment by vmanot** [comment]
@longbct I'm working on refactoring it (along with finalizing the API set for `CollectionView`). A bunch of other folks have asked for this as well - I'm really sorry for the delay. Am currently stretched between my clientele work and OSS work - so am pushing code as much as I can but I do want to find time to document it properly along with a few blog posts sometime this month.

**Comment by Kinark** [comment]
Ok so, where's the docs for CocoaList?
