### ISSUE TITLE
Named Color Support

### ISSUE THREAD

**Issue by Brett-Best** [SwiftUIX/SwiftUIX#24]
Named colours currently don’t work.

At the line linked below, calling `Mirror(reflecting: base).children.first?.value` gives the name of the color. It can then be used with `UIColor(named: xxx)`.

https://github.com/SwiftUIX/SwiftUIX/blob/master/Sources/Intermodular/Helpers/AppKit%20or%20UIKit/AppKitOrUIKitColor+.swift#L86

**Comment by vmanot** [comment]
Hey, thank you for raising the issue! Feel free to create a PR and merge this support in :)
