### ISSUE TITLE
CocoaScrollView pull to refresh dosen't work well with NavigationView's large title

### ISSUE THREAD

**Issue by jevonmao** [SwiftUIX/SwiftUIX#247]
When using CocoaScrollView's pull to refresh, the SwiftUI built in NavigationView's large title clips the CocoaScrollView and looks really bad. Is there a solution to this? Does SwiftUIX have a custom NavigationView?

**Comment by vmanot** [comment]
@jevonmao unfortunately I'm not sure what the best generic implementation for this is. Are there any good UIKit implementations you could point me towards? I could look into porting the best recommended UIKIt practices to my refresh control.

**Comment by jevonmao** [comment]
@vmanot I really don't know friend. This whole entire library is like a black box to me and I don't have a lot of experience with UIKit so I am afraid I can only report on the behaviors of this bug. Do you know the reason this is happening?

**Comment by vmanot** [comment]
I'm at my wits' end with `UIRefreshControl` - what an absolutely botched up API. Closing this ticket as I'm considering it out of scope for SwiftUIX.
