### ISSUE TITLE
need more document and examples #238

### ISSUE THREAD

**Issue by rahat14** [SwiftUIX/SwiftUIX#249]
trying to implement UICollectionView seems like there is a lack of documentation or Example. 
If you guys provide me an example i can write the DOC for it .

**Comment by vmanot** [comment]
@rahat14 the reason it's currently undocumented is because the API is still in flux and liable to change - I'm trying to finish it as soon as possible but don't want to release a rushed set of APIs. Closing this as a dupe of #238 for now.
