### ISSUE TITLE
How to not dismiss the keyboard

### ISSUE THREAD

**Issue by BenjiMandel** [SwiftUIX/SwiftUIX#252]
Is it possible with SwiftUIX to prevent the keyboard from dismissing automatically?

I am building a quiz app, and I don't want the keyboard to dismiss between questions.

Thx!

**Comment by vmanot** [comment]
@BenjiMandel where is it dismissing automatically? Which view are you referring to?

**Comment by BenjiMandel** [comment]
@vmanot i am not referring to a view specifically, I want to know of SwiftUIX adds the ability (with one of it's views/extensions) to prevent the keyboard to dismiss when a text field is active. 

It us maybe worded better as to have a text field(when it's shown) to always be the first responder, so that the keyboard will always be shown

**Comment by vmanot** [comment]
@benjaminfox ah unfortunately it's not possible to force the keyboard to show by itself. You could fake it with a hidden text field `CocoaTextField("", text: .constant("").isFirstResponder(true).hidden()` - but then the responder chain would be focused on that text field and not the one you want. You should look into [SwiftUI-Introspect](https://github.com/siteline/SwiftUI-Introspect) to accomplish what you want here - it is currently out scope for the project (I may add experimental introspection APIs soon but no guarantees).

**Comment by BenjiMandel** [comment]
Ok, thank you very much @vmanot
