### ISSUE TITLE
CocoaScrollView not showing contents on iOS 14, XCode 12.5

### ISSUE THREAD

**Issue by lilingxi01** [SwiftUIX/SwiftUIX#254]
Here is a minimal demo for reproducing the problem:

```
struct ContentView: View {
    var body: some View {
        CocoaScrollView(.vertical) {
            VStack {
                Text("123")
            }
        }
    }
}
```

iOS 14, iPhone 12 Pro Simulator, XCode 12.5, new SwiftUI App Lifecycle

The content of CocoaScrollView does not appear when the view is loaded.
But it does appear after switching to another app and switching back again.

Any idea on why and how to fix it?

**Comment by vmanot** [comment]
@lilingxi01 add `.fixeSize()` to your content (especially text).

**Comment by vmanot** [comment]
Closing this for now, please feel free to reopen if `.fixedSize()` hasn't fixed your issue.
