### ISSUE TITLE
Cocoatextfield crashing with a title

### ISSUE THREAD

**Issue by BenjiMandel** [SwiftUIX/SwiftUIX#255]
The `CocoaTextField` crashes my app when I add a placeholder like so:

`CocoaTextField("Placeholder", text: $viewModel.textFieldText)`

crash log: 
` Learn Chemistry[6332:238239] -[NSNull pointSize]: unrecognized selector sent to instance 0x1c2913560`

But when I have an empty string for the placeholder like so:
`CocoaTextField("", text: $viewModel.textFieldText)`

the view gets shown like normal

But when I tap on a button, which checks what was entered, and then empties the textFieldText variable for the next question(I am building a learning app), the app also crashes:

```
Learn Chemistry[6415:242807] [strings] ERROR: %@ %lld/%lld not found in table Localizable of bundle CFBundle 0x145605d30 </Users/benji/Library/Developer/CoreSimulator/Devices/C9BED2C0-B055-4B37-B1A9-F632755494BF/data/Containers/Bundle/Application/43294B6A-B784-4735-90DD-A288E13D528D/Learn Chemistry.app> (executable, loaded)
2021-05-20 18:22:38.132491+0200 Learn Chemistry[6415:242807] [strings] ERROR: Open Questions not found in table Localizable of bundle CFBundle 0x145605d30 </Users/benji/Library/Developer/CoreSimulator/Devices/C9BED2C0-B055-4B37-B1A9-F632755494BF/data/Containers/Bundle/Application/43294B6A-B784-4735-90DD-A288E13D528D/Learn Chemistry.app> (executable, loaded)
```

**Comment by vmanot** [comment]
@BenjiMandel this should be fixed on `master`, could you confirm?

**Comment by vmanot** [comment]
Closing this as this should be fixed, please reopen if it's still reproducible on `master`.

**Comment by BenjiMandel** [comment]
@vmanot I can confirm this is fixed on master. sorry for not replying.
