### ISSUE TITLE
Infinite scroll CollectionView with .onOffsetChange - scroll inertia lost when loading more data

### ISSUE THREAD

**Issue by schwjustin** [SwiftUIX/SwiftUIX#258]

**Comment by vmanot** [comment]
This is expected behavior in UICollectionView.

**Comment by schwjustin** [comment]
If it is expected behavior, how do apps like Instagram and Twitter maintain inertia while scrolling?

**Comment by vmanot** [comment]
@schwjustin they handle it using custom `UICollectionView` subclasses and/or custom `UICollectionViewLayout` subclasses. Some of them might not even be using collection views, I think Twitter is still maybe on UITableView (not sure, but just a hunch given that they have to maintain backwards compatibility).
