### ISSUE TITLE
CollectionView .onOffsetChange called again after data is fetched for infinite scrolling

### ISSUE THREAD

**Issue by schwjustin** [SwiftUIX/SwiftUIX#259]
Initially, I used this condition for fetching more data:

`
.onOffsetChange { offsetChange in
    if offsetChange.value(from: .bottomTrailing).y >= 0 && !model.isLoading {
        model.fetch()
}
`

but model.fetch() was being called once when the bottom of CollectionView was reached and again immediately after the data was loaded. So, I had to create a @State variable called toggle:

`
.onOffsetChange { offsetChange in
    if offsetChange.value(from: .bottomTrailing).y >= 0 && !model.isLoading && toggle {
        toggle = false
        model.fetch(true)
    } else if offsetChange.value(from: .bottomTrailing).y < 0 {
        toggle = true
    }
}
`

I think this is related to the other issue I submitted regarding losing inertia after more data is loaded.

**Comment by vmanot** [comment]
This is expected behavior, closing as it isn't a bug.
