### ISSUE TITLE
Activity Indicator Crash

### ISSUE THREAD

**Issue by Brett-Best** [SwiftUIX/SwiftUIX#26]
On iOS 13.0 I’m getting a crash:
Fatal error: Reading Environment<Optional<Color>> outside View.body: file
When accessing the `uiView.color = tintColor?.toUIColor()`

On iOS 13.1+, no crash is caused.

A workaround could be to disable tint color on iOS 13.0 only?

**Comment by vmanot** [comment]
Disabled it for < iOS 13.1.
