### ISSUE TITLE
Conformance of 'SearchBar' to 'View' is unavailable in application extensions for iOS

### ISSUE THREAD

**Issue by jfsagasti** [SwiftUIX/SwiftUIX#261]
Hi! :) we have an extension that uses the SearchBar. It was working without any problems before Xcode 12.5. The compilation error that throws now is:

Conformance of 'SearchBar' to 'View' is unavailable in application extensions for iOS.

What do you think it could be the best workaround for this? Thank you!

**Comment by vmanot** [comment]
@jfsagasti hi, thanks for reporting, could you fork it and see if removing some of the extension unavailability attributes on `SearchBar` fix the issue for you?

**Comment by jfsagasti** [comment]
@vmanot thanks for the quick answer! I've tried with a fork and removed the unavailable macros on the SearchBar file, but then other issues arises: 

![Captura de pantalla 2021-05-26 a las 18 02 23](https://user-images.githubusercontent.com/1671524/119701828-b2b60f80-be4c-11eb-8567-6a3c90c9ba48.png)

Are you planning to support this lib in the app extensions? I wonder how this worked before if those unavailable macros were there for some time. Do you know the reason? 😮 

Again, thank you! This library is amazing.

**Comment by Brett-Best** [comment]
@jfsagasti I can take a look if you make a sample project

**Comment by vmanot** [comment]
Closing for now, but please reopen if this problem still persists.
