### ISSUE TITLE
PaginationView - mutating the model results in "Index out of range" crash

### ISSUE THREAD

**Issue by geraldvoit** [SwiftUIX/SwiftUIX#263]
Hey,

I think there is a bug concerning PaginationView's currentIndex after mutating the model.

**Description** 

- It seems like the currentIndex won't be reset or adjusted (e.g. 0) after the model is replaced by an array of smaller page count and / or the model has completely different array items (--> **Identifiable**). 
  - Adjusting the currentIndex via the currentPageIndex binding along with the array (model) update did not work either.
- As a result, if the updated page count is lower than the currentIndex, the PaginationView crashes --> "Index out of range".

The attached Playground.swift file includes a showcase to reproduce the described behavior / crash.

[Playground.swift.zip](https://github.com/SwiftUIX/SwiftUIX/files/6566710/Playground.swift.zip)

**Steps to reproduce:**

- Xcode 12.5
- Simulator: iPhone 12 Pro / iOS 14.5
- Start App including [Playground.swift.zip](https://github.com/SwiftUIX/SwiftUIX/files/6566710/Playground.swift.zip)
- Tap the "+"-Button
- Swipe to the right (currentIndex = 1)
- Tap the "reload"-Button --> crash

**Console output:**

> Swift/Range.swift:304: Fatal error: Index out of range

**Debugger:** 

Stops at: UIHostingPageViewController : 61  

> viewController.rootView.page = content.content(content.data[viewController.rootView.index])

**What I expected:**

- currentIndex is reset to 0, if the array (model) is replaced by different values (**Identifiable**)
- If the model updates because of an ".append()", currentIndex should not be reset because it points to the same page (same id - **Identifiable**)

**Comment by vmanot** [comment]
@geraldvoit thank you for such a well-written and detailed bug report, this has now been fixed on `master`!
