### ISSUE TITLE
Regression after Xcode 13 beta SwiftUIX fails to compile

### ISSUE THREAD

**Issue by jevonmao** [SwiftUIX/SwiftUIX#267]
My app fails to compile due to SwiftUIX internal errors after Xcode 13 Beta. It compiles fine on latest Xcode 12. I created a new empty Xcode 13 beta project and was able to reproduce the exact same error. 

However, the error only occurs when building for iOS, not macOS. I understand it's a crazy time with the dub dub 2021 and we are only on the 1st beta, so it might take time for you to fix this bug. 

## Reproduce
1. Create new empty Xcode project
2. Add SwiftUIX through SPM
3. Compile on iOS will always fail

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/64660730/121754351-42a0be00-cac9-11eb-9e08-97d0436d5d57.png">

**Comment by vmanot** [comment]
@jevonmao this is fixed on `master`, I'll be cutting out a new release tomorrow as well. It would seem that you're currently on version `0.0.6` as opposed to `master`.

**Comment by jevonmao** [comment]
@vmanot Thank you!

**Comment by vmanot** [comment]
@jevonmao you should update to `0.0.7` - just released a new version :)
