### ISSUE TITLE
cannot change background color of any view inside windowOverlay

### ISSUE THREAD

**Issue by X901** [SwiftUIX/SwiftUIX#268]
Hi , 
I notice if I put background color on any view inside windowOverlay it won't change
always will show white color even in darkMode

**Comment by vmanot** [comment]
@X901 could you attach a sample repro snippet?

**Comment by X901** [comment]
@vmanot after I use it for a while I notice the issue is it always follow system color 
for example if my system is dark model , but I force my app to be light mode
it will be dark mode won't change to light mode 
my app have theme system, light , dark
if I use system everything is working fine , but If my system is light and force my app to be dark , or vice versa
it won't work (won't change)
