### ISSUE TITLE
AttributedText height problems when put in List or ScrollView

### ISSUE THREAD

**Issue by kevinrenskers** [SwiftUIX/SwiftUIX#27]
This doesn't show anything:

```
struct ContentView: View {
  var body: some View {
    ScrollView {
      AttributedText("Hello World\nSecond Line")
    }
  }
}
```

And when you put it in a List instead of a ScrollView, it only shows the first line.

**Comment by vmanot** [comment]
I've unfortunately not been able to understand why this is happening :(

Feel free to poke around and see if you can improve the layout behavior.

**Comment by judomat** [comment]
try using 
```swift
view.setContentHuggingPriority(.defaultHigh, for: .horizontal)
view.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
view.setContentHuggingPriority(.defaultHigh, for: .vertical)
view.setContentCompressionResistancePriority(.defaultHigh, for: .vertical)
```
in the makeUIView() method of UIViewRepresentable.
You should also add them in the TextView, because right now it takes up all the available space even if there is only a short text in it
