### ISSUE TITLE
CocoaScrollView - Disable contentInsets scrolling

### ISSUE THREAD

**Issue by daweido** [SwiftUIX/SwiftUIX#275]
Hey all,

I wondered if there was a way to disable scrolling on the content inset but leave the scrolling gesture enabled on the content itself?

Thanks
daweido

**Comment by vmanot** [comment]
@daweido is this possible in UIKit? Can definitely expose it if so. If not, I may close this down as an out of scope feature-request.

**Comment by vmanot** [comment]
Closing this as it doesn't seem to be an out-of-the-box feature from UIKit. I'm happy to consider a PR (the API for this would have to be really concise though), but this is out of scope for SwiftUIX.
