### ISSUE TITLE
TextView moves cursor to the end after return key

### ISSUE THREAD

**Issue by skryshi** [SwiftUIX/SwiftUIX#28]
In TextView, pressing return key twice, moves the cursor to the bottom of the TextView. Which makes it unusable. Any ideas how to fix it?

On XCode 11.3.1. In simulator and on device. Try it with this trivial code. Run it and type in: return key, some text, scroll the cursor to the top, return key.

```
import SwiftUI
import SwiftUIX

struct ContentView: View {
    @State private var text = ""
    
    var body: some View {
            TextView("type in", text: $text)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

**Comment by ggruen** [comment]
I ran into this issue when assembling my own version of `TextView` before finding SwiftUIX. The answer was to record and put back the cursor in `updateUIView`. Replacing `updateUIView` in TextView.swift with the below _should_ fix the cursor placement issue:

    func updateUIView(_ textView: UITextView, context: Context) {
        if let font = context.environment.font, font.toUIFont() != textView.font {
            textView.font = font.toUIFont()
        }

        // Record where the cursor is
        var cursorOffset: Int?
        if let selectedRange = textView.selectedTextRange {
            cursorOffset = textView.offset(from: textView.beginningOfDocument, to: selectedRange.start)
        }

        // Update the field - this will displace the cursor
        textView.text = text

        // Put the cursor back
        if let offset = cursorOffset,
            let position = textView.position(from: textView.beginningOfDocument, offset: offset) {
            textView.selectedTextRange = textView.textRange(from: position, to: position)
        }
    }

Disclaimer: The above code is from the "TextEditorView" struct I wrote. It works there, but I haven't tested it in SwiftUIX's "TextView".

**Comment by vmanot** [comment]
Fixed. Thank you @ggruen for the fix, it worked like a charm!

**Comment by skryshi** [comment]
Thank you, @ggruen. It almost works. The cursor no longer jumps, but the view still sometimes jumps to the bottom. Hard to pinpoint the exact conditions when it happens, but if you play with entering text and newlines, it will occasionally happen.
