### ISSUE TITLE
PaginationView SafeArea issues

### ISSUE THREAD

**Issue by shtnkgm** [SwiftUIX/SwiftUIX#281]
I can't ignore the device's SafeArea when I apply the `ignoresSafeArea()` modifier to the `PaginationView`.
How can I ignore the Safe Area?

```swift
PaginationView(axis: .horizontal, showsIndicators: false) {
    ForEach(items, id: \.self) {item in
        Text("\(item)")
    }
}
.ignoresSafeArea()
```

This issue is likely to be related to the following:
https://twitter.com/b3ll/status/1193747288302075906

**Comment by vmanot** [comment]
Can you try using `_fixSafeAreaInsets()` inside `PaginationView`? That should fix it.

**Comment by hyalpha** [comment]
Seems not working. Or am I using it at the wrong way?

`PaginationView(axis: .horizontal) {
            Text("One")
                .frame(maxWidth:.infinity, maxHeight: .infinity)
                .background(Color.red)
                .ignoresSafeArea(edges: .bottom)
                ._fixSafeAreaInsets()
            Text("Two")
            Text("Three")
        }`
