### ISSUE TITLE
TextView holding reference to NSView

### ISSUE THREAD

**Issue by ggruen** [SwiftUIX/SwiftUIX#29]
Hi - great module; thanks for it! :)

I'm running into a weird issue with `TextView` running on macOS on a master/detail view: When there's a `TextView` in the detail view, the contents of the `TextView` continue to show (and edit) the first item selected in the list view, even though the rest of the detail view has changed.

Gif of the issue: https://www.dropbox.com/s/2cp6upj7twfi601/TextView.gif

To set up to reproduce:
- Make a new project in Xcode, e.g. "TextViewTest", selecting macOS > App and checking the box to use SwiftUI. Deselect Core Data, CloudKit, tests, etc.
- Go to File > Swift Packages > Add Package Dependency and add SwiftUIX
- Copy/Paste the code below to replace what's in `ContentView.swift`

To reproduce:
- Build and run the app
- Click on one of the items in the list on the left
- Enter a note on the right
- Click on one of the other items in the list of the left

Expected result:
- The detail on the right should update to show the new selection's name (e.g. "Fish") and the placeholder text to enter a new note

Actual result:
- The detail on the right updates the name, but the previously entered note remains.

Notes:
- The note is still editing the note property of the original object.
- If you click outside of one of the options (that is, select no option), then click an option again, TextView shows that option's note field (and will persist to until you select nothing again).
- I'm not working on a meal selection app, I'm just hungry. ;-)

```
    import SwiftUIX

    struct ContentView: View {
        @State var selection: UUID?

        var meals = [
            Meal(name: "Fish"),
            Meal(name: "Steak"),
            Meal(name: "Chicken")
        ]

        var selectedMeal: Meal? {
            meals.first(where: {$0.id == selection})
        }

        var body: some View {
            HStack {
                List(selection: $selection) {
                    ForEach(meals) { meal in
                        Text(meal.name).tag(meal.id)
                    }
                }

                if selectedMeal != nil {
                    DetailView(meal: selectedMeal!)
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
    }

    struct DetailView: View {
        @ObservedObject var meal: Meal

        var body: some View {
            VStack(alignment: .leading) {
                Text("Meal: \(meal.name)")
                TextView("Enter some notes", text: $meal.note)
            }

        }
    }

    class Meal: Identifiable, ObservableObject, Hashable {
        static func == (lhs: Meal, rhs: Meal) -> Bool {
            lhs.id == rhs.id
        }

        func hash(into hasher: inout Hasher) {
            hasher.combine(id)
        }

        var id = UUID()
        var name: String = ""
        var note: String = ""

        init(name: String) {
            self.name = name
        }
    }

    struct ContentView_Previews: PreviewProvider {
        static var previews: some View {
            ContentView()
        }
    }
```

**Comment by vmanot** [comment]
This should be fixed now.
