### ISSUE TITLE
Presenter always nil

### ISSUE THREAD

**Issue by mistralaix** [SwiftUIX/SwiftUIX#292]
Hi, I was using the presenter on my previous project with the CocoaHostingController and everything was working as expected.
I wanted to switch on this new version and use a PresentationView instead. The presenter is always nil.
Am I missing something ?
Btw I also tried to use the StackNavigationView and I have the same problem.
``` swift
import SwiftUI
import SwiftUIX

@main
struct iOSApp: App {
    
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    @Environment(\.presenter) private var presenter
    
	var body: some Scene {
        WindowGroup {
            PresentationView {
                Text("Test")
                    .onTapGesture {
                        print(presenter) // presenter is always nil
                        presenter?.present(RegisterView())
                    }
            }
        }
	}
}
```

Thanks everyone for your help!

**Comment by vmanot** [comment]
The issue here is that you're reading the environment of `iOSApp`, which is _not_ wrapped in a `PresentationView`. The solution is to create a `ContentView`, and in your app's body wrap it like so: `PresentationView { ContentView() } }`. This will ensure that `ContentView`'s environment has a valid `presenter` present.

**Comment by mistralaix** [comment]
In order to simplify the example I just posted it in the iOS app but it was in another view before.
So I just tried to follow your comment:
``` swift
@main
struct iOSApp: App {
    
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
	var body: some Scene {
        WindowGroup {
            PresentationView { ContentView() }
        }
	}
}

struct ContentView: View {
    
    @Environment(\.presenter) private var presenter
    
    var body: some View {
        Text("Test")
            .onPress {
                print(presenter) // presenter is nil
                presenter?.present(RegisterView())
            }
    }
}
```

**Comment by vmanot** [comment]
<img width="1155" alt="Screen Shot 2021-08-02 at 7 28 24 PM" src="https://user-images.githubusercontent.com/5306992/127873471-16c20212-31f6-4875-8d84-dea20a9b0441.png">

Hmm.. it worked for me? This is running on Xcode 12.5.1, iPhone 12 Pro (14.5) sim.

**Comment by skywalkerlw** [comment]
The drawback of  `presenter` is it does not support presenting another modal when a modal is presented.
