### ISSUE TITLE
Xcode 13 Beta 4 issues

### ISSUE THREAD

**Issue by DominikButz** [SwiftUIX/SwiftUIX#295]
Hi, my project is refusing to build for iOS 15, Xcode 13 beta 4. 
The following errors are raised:

- UIViewControllerLifecycleEvent > func makeUIViewController(context: Context)
   UIViewControllerType()  // missing argument for parameter rootView

- CocoaTextField >      @ObservedObject var keyboard = Keyboard.main  // Keyboard is unavailable in application extensions for iOS
- List ++ > extension List ...  Contextual closure type '(Data.Element, Bool) -> RowContent' expects 2 arguments, but 1 was used in closure body

Thanks for checking these errors out and possibly releasing an update for iOS 15. thanks

regards
Dominik

**Comment by vmanot** [comment]
@DominikButz this is fixed on `master` (and actually should be fixed on the last release as well). Could you try updating your version dependency for SwiftUIX?

**Comment by DominikButz** [comment]
OK - strange, I thought I updated the package. Now Xcode 13 Beta 4 shows errors in another package, but not SwiftUIX any more...  thanks
