### ISSUE TITLE
Cannot be used as a dependency for packages that support lower os versions

### ISSUE THREAD

**Issue by maximkrouk** [SwiftUIX/SwiftUIX#296]
The package specifies
```swift
platforms: [
  .iOS(.v13),
  .macOS(.v10_15),
  .tvOS(.v13),
  .watchOS(.v6)
]
```
So it cannot be imported to packages with lower requirements.

The solution is to remove these constraints, add #canImport(SwiftUI) checks and @available attributes to implementations
> _there were some issues with [RAC-TCA](https://github.com/trading-point/reactiveswift-composable-architecture) when #canImport wasn't used, they could be fixed at the client by specifying SwiftUI in target explicitly or something, but clients probably should not care about these workarounds, so it's better to add both checks_

**Comment by vmanot** [comment]
@maximkrouk this is out of scope for the project unfortunately.

**Comment by maximkrouk** [comment]
> _Btw I meant, that apps, that use spm-based modularization and do support lower iOS versions_ (_but for some new features they use SwiftUI_) _might not be able to use SwiftUIX_

**Comment by jevonmao** [comment]
@vmanot Would you care to elaborate on why not? I'm interested in this proposal, and it is a very common issue for SwiftUI libraries, some apps are slowly migrating to SwiftUI. But the high deployment target does not allow adding the library at all. Is there a specific issue for SwiftUIX?
