### ISSUE TITLE
Create docs branch so I can open a PR? =D

### ISSUE THREAD

**Issue by kevinrpb** [SwiftUIX/SwiftUIX#3]
Hi, I thought the project would eventually need a docs page if it continues to grow (as opposed to having a giant README hehe), so I [started one](https://kevinrpb.github.io/SwiftUIX/).

However, I don't have anywhere to create a PR to (I used a new `docs` branch). Could you create this empty branch so I can send a PR? =)

**Comment by vmanot** [comment]
Looks good! Could you reach out to me via iMessage/Mail (vatsal.manot@yahoo.com)? There are a few things I'd like to discuss. I've purchased a domain name for SwiftUIX, so we can host this up there :)
