### ISSUE TITLE
How to change the color of some View when using VisualEffectBlurView(vibrancyStyle: .fill) ?

### ISSUE THREAD

**Issue by LeonManolo** [SwiftUIX/SwiftUIX#302]
Basically what Im trying to achieve is to change the colors only for some specific views.
Is there a way to change the color for just some specific Views when using vibrancyStyle: .fill?

Example
```swift
                        VisualEffectBlurView(blurStyle: .systemUltraThinMaterial, vibrancyStyle: .fill){
                            Text("Test Text")
//This text in white?
                            Text("this text should be white")
                                .foregroundColor(.white)
                        }
```

**Comment by vmanot** [comment]
@LeonManolo unfortunately this is not supported at the moment. Due to constraints in APIs offered by SwiftUI, I can't enable vibrancy effects for text/images within a blur view.
