### ISSUE TITLE
CocoaTextField does not recognise `isEditing` updates (Xcode 12.5.1)

### ISSUE THREAD

**Issue by marius-se** [SwiftUIX/SwiftUIX#303]
When setting `isEditing` to false (e.g. by tapping a button) `CocoaTextField` does not recognise the change of the `isEditing` property.

Minimal setup with Xcode 12.5.1:
```
struct ContentView: View {
    @State private var value: String = ""
    @State private var isEditing: Bool = false

    var body: some View {
        VStack {
            CocoaTextField("Placeholder", text: $value, isEditing: $isEditing)
            Button("End editing", action: { isEditing = false })
        }
        .onChange(of: isEditing, perform: { value in
            print("isEditing: \(isEditing)")
        })
    }
}
```

**Comment by marius-se** [comment]
I investigated a little bit further and did some major changes to the initial GitHub issue. :)

**Comment by marius-se** [comment]
Update: I noticed that in `CocoaTextField.swift` line 260-276 none of the if statements succeed when setting `isEnabled` to `false`.

**Comment by vmanot** [comment]
@marius-se use `.focused($isEditing)` instead of `isEditing` in the init.

**Comment by marius-se** [comment]
Okay thanks!
