### ISSUE TITLE
WebView fails for iOS 14 StateObject when building for iOS 13

### ISSUE THREAD

**Issue by kyle-beard-wex** [SwiftUIX/SwiftUIX#304]
The Intramodular WebView is failing for `'StateObject' is only available in iOS 14.0 or newer` when the target version is set to below iOS 14.0. Could we add `@available(iOS  14.0, *)` to that struct?

**Comment by vmanot** [comment]
@kyle-beard-wex this is now fixed, thanks for reporting!

**Comment by kyle-beard-wex** [comment]
Glad to contribute! Thanks for the speedy fix.
