### ISSUE TITLE
Xcode 13 RC issue

### ISSUE THREAD

**Issue by X901** [SwiftUIX/SwiftUIX#306]
I cannot run my project because of this issue

![Screen Shot 2021-09-15 at 1 11 18 PM](https://user-images.githubusercontent.com/16876982/133423472-df01069c-7259-4a5f-b855-4f1f9f4a5389.jpeg)

**Comment by amoshsueh** [comment]
Same here

**Comment by vmanot** [comment]
@X901 which tag are you on? This should be fixed on `master`.

**Comment by BenSullivan-iOS** [comment]
Same here on v0.0.8 on SPM. How would I go about knowing the tag or changing to master?

**Comment by X901** [comment]
> @X901 which tag are you on? This should be fixed on `master`.

I'm on the master

**Comment by vmanot** [comment]
@X901 it can't be the tip of master because the screenshot you've attached doesn't match `List++.swift` in the current repo.

**Comment by BenSullivan-iOS** [comment]
I cleaned & cleared derived data and it's working now! 👍

**Comment by vmanot** [comment]
@BenSullivan-iOS thanks for confirming. Closing this ticket now.

**Comment by X901** [comment]
it worked now , thank you 
I notice the SPM was using old version by default change it to master

**Comment by recurrence** [comment]
This is still happening on the master branch pointed at macOS apps.

**Comment by uniqby** [comment]
Same issue in XCode Version 13.2 (13C90) for macOS target
