### ISSUE TITLE
XCode 13 RC Archive Error

### ISSUE THREAD

**Issue by skywalkerlw** [SwiftUIX/SwiftUIX#311]
My SwiftUI target is iOS 14 and errors only happen on a release build archive.

![image](https://user-images.githubusercontent.com/2090084/134583197-345b6a93-4395-48c4-9974-fb2927451ec4.png)

**Comment by vmanot** [comment]
@skywalkerlw `master` should be archiving for you. Could you try again?

**Comment by skywalkerlw** [comment]
yes, finally, i found it came a bug from KingFisher framework: https://github.com/onevcat/Kingfisher

**Comment by vmanot** [comment]
@skywalkerlw gotchya, thanks for confirming.
