### ISSUE TITLE
VisualEffectBlurView crash in iOS 15 : Thread 1: Simultaneous accesses to 0x10a330050, but modification requires exclusive access

### ISSUE THREAD

**Issue by unitedadi** [SwiftUIX/SwiftUIX#313]
var intensity: Double {
        didSet {
            if let animator = blurEffectAnimator {
                animator.fractionComplete = .init(intensity)
            }
        }
    }

**Comment by vmanot** [comment]
This should be fixed on `master` now. Thanks for reporting!
