### ISSUE TITLE
Support for Xcode 13.0 (13A233)

### ISSUE THREAD

**Issue by SagarUnagar** [SwiftUIX/SwiftUIX#314]
Updated Xcode to 13 (stable version from App Store). Stuck at this compile error. Could you please help me out? Followed this thread #310 as well. Tried with the latest tag - 0.0.9. Still, doesn't solve for the particular Xcode version, which I am in. 
<img width="1155" alt="compile issue" src="https://user-images.githubusercontent.com/16893693/135274778-15acc55a-18c1-4076-bde3-d4260d661805.png">

**Comment by vmanot** [comment]
@SagarUnagar I'm on the App Store version as well, you should update to `master`.

**Comment by vmanot** [comment]
@SagarUnagar I also just confirmed by building it on Xcode 13, closing this ticket. Please reopen if this issue persists.

**Comment by SagarUnagar** [comment]
Hi Vatsal, Thank you for your response. 

Issue is still persisted. I also tried using `master` but still getting same error.

<img width="641" alt="package dependency" src="https://user-images.githubusercontent.com/16893693/135317988-6e15c9de-b980-49a3-adf5-9f8628f4a8cf.png">

**Comment by vmanot** [comment]
@SagarUnagar which file is it failing on for you? Could you give me the exact file & line number?

**Comment by SagarUnagar** [comment]
Hi @vmanot

Error is in Sources/Intermodular/Helpers/UIKit/UIViewControllerLifecycleEvent.swift at line 77.

**Comment by vmanot** [comment]
@SagarUnagar no idea why this is causing an issue. It's not even used in SwiftUIX (was unfinished code), so I've straight up removed it. I think this may've been a red herring and some other framework/dependency in your project could be causing issues though.
