### ISSUE TITLE
How to listen to selected text and changes to selection using CocoaTextField?

### ISSUE THREAD

**Issue by thegitparticle** [SwiftUIX/SwiftUIX#319]
I want to trigger a function or variable change of the selected text whenever user selects a portion of the typed text string and if they move the selection right or left to change the range of selected portion.

Is it possible to achieve using CocoaTextField or how do I get it even with UIKit TextField?

**Comment by vmanot** [comment]
@thegitparticle honestly not sure, but I can consider this feature enhancement request if possible with UIKit.

**Comment by thegitparticle** [comment]
solved it using this - https://github.com/kyle-n/HighlightedTextEditor
