### ISSUE TITLE
CocoaList  当且仅当第三条数据的发生变化而不更新，

### ISSUE THREAD

**Issue by shaokui-gu** [SwiftUIX/SwiftUIX#327]
![image](https://user-images.githubusercontent.com/83857593/139654559-5173e12e-9534-4f19-8f6f-8b66ac68fcbd.png)

发现修改数据中的某条数据内容，数据id唯一，当且仅当第三条数据的发生变化而不更新，注释部分这个判定生效，不是第三条就没有任何问题，到目前我没有跟踪到具体的原因，还是说可能我自己的代码有问题，但我仅仅使用了一个model list 然后去修改它的某条数据

**Comment by vmanot** [comment]
@shaokui-gu apologies, I can't make out the issue from Google Translate here. Could you try re-opening in English? If someone looking at this issue is bilingual I'd really appreciate a translation.
