### ISSUE TITLE
CocoaScrollView decelerationRate

### ISSUE THREAD

**Issue by nasru** [SwiftUIX/SwiftUIX#329]
Hello there. I want to make some changes in CocoaScrollView but I couldn't find where to do it. things i want to do:
```
    scrollView.bounces = false
    scrollView.decelerationRate = UIScrollView.DecelerationRate.fast
```

**Comment by vmanot** [comment]
@nasru enabling/disabling bounce is accessible via `scrollBounceDisabled(_:)`. As for deceleration rate, I'll add the ability to expose it.

**Comment by nasru** [comment]
I m used it scrollBounceDisabled. But did not working. Did not disabled bohncing

**Comment by vmanot** [comment]
@nasru it only works with `CocoaScrollView`. Are you using it with SwiftUI's `ScrollView` or with `CocoaScrollView`?

**Comment by vmanot** [comment]
@nasru I've added `CocoaScrollView.decelerationRate(_:)`
