### ISSUE TITLE
I have an error, as shown

### ISSUE THREAD

**Issue by maik-he** [SwiftUIX/SwiftUIX#336]
![WX20211221-104040](https://user-images.githubusercontent.com/10544330/146861780-1e4f4b7e-e4a9-47dc-b21c-70c3ead50cb8.png)
![WX20211221-104407](https://user-images.githubusercontent.com/10544330/146862026-24bc9d7b-d098-49fe-8269-53e7b56fc5b1.png)

**Comment by vmanot** [comment]
@maik-he you're on an extremely old version/commit of SwiftUIX, these issues were fixed a while ago. Please update either to the latest version (0.1.1) or the latest commit on `master`.

**Comment by maik-he** [comment]
Thank you very much. I'll try

**Comment by vmanot** [comment]
@maik-he no problem, please feel free to reopen this issue if you're still unable to compile.
