### ISSUE TITLE
ModalPresentationStyle: form doesn't work on the iPad

### ISSUE THREAD

**Issue by richardtop** [SwiftUIX/SwiftUIX#337]
What's the correct way to use `modalPresentationStyle`? I'm currently modifying the content of the `sheet` SwiftUI call but it doesn't help and the view seems to be presented with the standard PageSheet design:
```Swift
        .sheet(isPresented: $modalPresented) {
            MyModalPopup()
                .modalPresentationStyle(.form)
        }
```

![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2021-12-21 at 17 12 44](https://user-images.githubusercontent.com/8013017/146953741-00968e20-c8bb-4a9c-ac4c-b78e8980138e.jpg)

**Comment by vmanot** [comment]
This modifier only works with SwiftUIX's PresentationLink for now, it's not possible to override Apple's modifiers.
