### ISSUE TITLE
AppActivityView crashing when not shown as .sheet()

### ISSUE THREAD

**Issue by Mcrich23** [SwiftUIX/SwiftUIX#342]
I have tried things other than .sheet(), every time I do, it crashes the app throwing this error: `UIActivityViewController can only be used modally or as contentViewController in popover on iPad`. Is there anyway to get around this? I don't like using the full sheet instead of the typical half sheet. Pls help.

**Comment by vmanot** [comment]
@Mcrich23 I'm not sure what the solution here is, maybe using the new iOS 15 sheet APIs to create a half-height modal? Closing this issue as it is out-of-scope to fix, but feel free to comment here/reopen if you find a fix - would be happy to merge it in.
