### ISSUE TITLE
PageViewController swipe ignores SwiftUI's navigationBarHidden(true)

### ISSUE THREAD

**Issue by shywoody** [SwiftUIX/SwiftUIX#343]
when I swipe while the navigation bar is hidden, it reappears.

**Comment by shywoody** [comment]
be like ,[this situation](https://stackoverflow.com/questions/69883830/uipageviewcontroller-swipe-ignores-swiftuis-navigationbarhiddentrue), could u give some suggestions？😊

**Comment by vmanot** [comment]
@shywoody could you upload a test project demonstrating this? I can take a look at it and attempt to patch it.

**Comment by shywoody** [comment]
`import SwiftUI
import SwiftUIX

private struct TestRedView: View{
    var body: some View{
        Color.red.opacity(0.3)
            
    }
}

private struct TestBlueView: View{
    var body: some View{
        Color.blue.opacity(0.3)
            .edgesIgnoringSafeArea(.all)
    }
}

extension TestErrorView {
    func mainTestView() -> some View{
//        let a = AnyView(TestRedView()).navigationBarHidden(true)
//        let b = AnyView(TestBlueView()).navigationBarHidden(true)
        let c = AnyView(TestRedView())
        let d = AnyView(TestBlueView())

        return PaginationView(pages: [c, d])
            .navigationBarTitle(Text("Test"), displayMode: .inline)
            .navigationBarHidden(true)
            .edgesIgnoringSafeArea(.all)
    }
}


struct TestErrorView: View {
    var body: some View {
        
        NavigationView{
            
            NavigationLink(destination: mainTestView()) {
                Text("click")
            }
        }

    }
}`

**Comment by shywoody** [comment]
> @shywoody could you upload a test project demonstrating this? I can take a look at it and attempt to patch it.

when i use pageController contain c & d ，swipe will show navigationBar， i think UIHostingControllers have c & d.  a & b can be nomal

**Comment by vmanot** [comment]
@shywoody fix this by putting a `.hideNavigationBar()` in your page views.

```swift
extension TestErrorView {
    func mainTestView() -> some View{
        //        let a = AnyView(TestRedView()).navigationBarHidden(true)
        //        let b = AnyView(TestBlueView()).navigationBarHidden(true)
        let c = AnyView(TestRedView())
        let d = AnyView(TestBlueView())
        
        return PaginationView(pages: [c.hideNavigationBar(), d.hideNavigationBar()])
            .navigationBarTitle(Text("Test"), displayMode: .inline)
            .navigationBarHidden(true)
            .edgesIgnoringSafeArea(.all)
    }
}
```

This fixed it for me.
