### ISSUE TITLE
Question: How do I do the last step of installation in xcode 13

### ISSUE THREAD

**Issue by huydinhle** [SwiftUIX/SwiftUIX#346]
```
Open the Project settings, add SwiftUI.framework to the Linked Frameworks and Libraries, set Status to Optional.
```

Can someone show me the pictures of how to do this?

**Comment by vmanot** [comment]
@huydinhle go to Targets → Build Phases → Link Binary With Libraries, and you should see a column called "Status" for each linked library. Mark SwiftUIX as Optional.

Hope this helps :)

**Comment by huydinhle** [comment]
Thank you it does work, but when I do `import SwiftUIX`I keep getting no such module error. Any idea why?

**Comment by navtoj** [comment]
The `Status` column does not show for me. I only see the `Embed` column.

![Screenshot 2024-08-26 at 12 11 21 AM](https://github.com/user-attachments/assets/85d8d104-c131-482a-906d-a9875d7089b8)

![Screenshot 2024-08-26 at 12 12 10 AM](https://github.com/user-attachments/assets/4690eb31-acff-4118-965f-06e499f47daf)

Which option should I choose?
