### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by writing-shed** [SwiftUIX/SwiftUIX#347]
I'm getting this error when compiling SwiftUIX with Xcode 13.3 beta

**Comment by vmanot** [comment]
@writing-shed are you on Xcode 13.3b2? `master` is compiling fine for me.

**Comment by writing-shed** [comment]
Using 13.3b2. Here is the log:

[Build Write!_2022-02-10T12-03-35.txt](https://github.com/SwiftUIX/SwiftUIX/files/8040790/Build.Write._2022-02-10T12-03-35.txt)
[](url)

**Comment by vmanot** [comment]
> Using 13.3b2. Here is the log:
> 
> 
> 
> [Build Write!_2022-02-10T12-03-35.txt](https://github.com/SwiftUIX/SwiftUIX/files/8040790/Build.Write._2022-02-10T12-03-35.txt)
> 
> [](url)

I think you might be on an older commit - I'd fixed the segfault the day Xcode 13.3b1 was released.

**Comment by writing-shed** [comment]
It is defo using v0.1.1. I removed the package from the project and reinstalled but it still fails.

[
<img width="807" alt="Screenshot 2022-02-10 at 12 52 42" src="https://user-images.githubusercontent.com/25199371/153412312-60a7f4f2-fe1f-48a6-b575-39ef06fd8747.png">
](url)

**Comment by writing-shed** [comment]
It's been working fine with 13.2.1. It only started failing when I installed the latest beta.

**Comment by bdashore3** [comment]
I'm also getting this error when trying to build with XCode 13.3b2

**Comment by bdashore3** [comment]
[SwiftUIX_master_XCode_133b2.txt](https://github.com/SwiftUIX/SwiftUIX/files/8041335/SwiftUIX_master_XCode_133b2.txt)

**Comment by bdashore3** [comment]
Update: Was able to fix this by forcibly triggering an update of the package from XCode. Build of SwiftUIx succeeds with warnings.

To update: `File > packages > Update to latest package versions`

**Comment by writing-shed** [comment]
Tried that but still failing. Did get this though:

/Users/writingshedprod/Library/Developer/Xcode/DerivedData/Write!-gxlgsjhdkgcwhpbsfahtmlirlqrl/SourcePackages/checkouts/SwiftUIX/SwiftUI.UIHostingController:17:17: Instance method 'sizeThatFits(in:)' isolated to global actor 'MainActor' can not satisfy corresponding requirement from protocol 'AppKitOrUIKitHostingControllerProtocol'

**Comment by writing-shed** [comment]
Added it by branch master and it worked so thanks
