### ISSUE TITLE
Cannot find 'CocoaTextField' in scope

### ISSUE THREAD

**Issue by rosenbergm** [SwiftUIX/SwiftUIX#350]
hi, i've installed SwiftUIX following the installation guidelines and i'm getting this error when trying to use the `CocoaTextField` view.

<img width="647" alt="Screenshot 2022-02-20 at 17 50 21" src="https://user-images.githubusercontent.com/10347191/154854030-aed01eca-5e3a-46b3-80f9-4b562ab548c4.png">

i have imported SwiftUIX at the top of the file and also tried to use other views, which functioned flawlessly.

when typing the name of the view, i am getting hints from xcode, saying this. it might be a clue for this problem's solution but since i'm definitely not a swift developer, i have no idea what is happening.

<img width="430" alt="Screenshot 2022-02-20 at 17 51 18" src="https://user-images.githubusercontent.com/10347191/154854074-a1ff410c-6b78-4344-9ec4-50f1c6fef151.png">

my xcode version: 13.2.1 (13C100)

thank you for help!!

**Comment by vmanot** [comment]
@rosenbergm is this for a watchOS app? I'm able to use `CocoaTextField` without an issue when building an iOS target.

**Comment by rosenbergm** [comment]
oh, sorry to mention – i'm building for macOS

**Comment by vmanot** [comment]
@rosenbergm `CocoaTextField` is not supported on macOS at the moment unfortunately. I'd love to write an AppKit port but just don't have the bandwidth at the time. If you feel like you can contribute to that end, am happily accepting PRs.

**Comment by rosenbergm** [comment]
ah, that sucks... i am a horrible swift developer so i'll rather stay away from submitting swift pull requests. thanks for maintaining this awesome library!

**Comment by vmanot** [comment]
@rosenbergm no problem! I'll be sure to ping here if I get any traction on a macOS variant of `CocoaTextField` :)
