### ISSUE TITLE
CocoaTextField keyboardType

### ISSUE THREAD

**Issue by Maedeh-saam** [SwiftUIX/SwiftUIX#353]
For CocoaTextField, .keyboardType(.numberPad) not work
![Screen Shot 2022-03-08 at 11 00 13 AM](https://user-images.githubusercontent.com/69032649/157188458-e0231f8b-e0a1-4b87-97a4-ec29d891ae9b.png)

**Comment by vmanot** [comment]
@Maedeh-saam move the `.keyboardType(.numberPad)` modifier to be placed right after `.isFirstResponder(currentFocus == 0)`, it should work.
