### ISSUE TITLE
[Question] How to set large title view?

### ISSUE THREAD

**Issue by amadeu01** [SwiftUIX/SwiftUIX#36]
I tried to use `navigationBarTitleView(_: displayMode)` to add a

```swift
NavigationView {
                List(emojiList, id: \.self) {
                    Text($0)
                }.navigationBarTitleView(
                    VStack {
                        Text("My Title")
                        Text("My sub-title").font(.subheadline)
                    }.height(84).width(200),
                    displayMode: .large
                )
            }.tabItem {
                Image(systemName: "star")
            }
```
<p float="left">
<img src="https://user-images.githubusercontent.com/11631092/76686293-1f9f0a00-65f9-11ea-8c22-b88e7ab5410c.png" width="300">

<img src="https://user-images.githubusercontent.com/11631092/76686345-71e02b00-65f9-11ea-8713-48003d4ec853.png" width="300">
</p>

However, it seems that the LargeTitle is not set, and only the view in the centre is set, which would be the behaviour after the user had scrolled -- so the large title would be collapsed.

Is there a way of setting a large title view that will collapse?

## Refs

[How can I add a custom view on the large title view of UINavigationBar introduced in iOS11](https://stackoverflow.com/questions/46620068/how-can-i-add-a-custom-view-on-the-large-title-view-of-uinavigationbar-introduce

[Custom title view as large title in iOS 11 new navigation bar](https://stackoverflow.com/questions/45043946/custom-title-view-as-large-title-in-ios-11-new-navigation-bar)

**Comment by vmanot** [comment]
It's not possible to do so with the current implementation, but I'd love it if you could create a PR for this =)

**Comment by vmanot** [comment]
Closing this issue as it is currently out-of-scope.
