### ISSUE TITLE
@PersistentObject alert "Modifying state during view update, this will cause undefined behavior".

### ISSUE THREAD

**Issue by BugMonkey** [SwiftUIX/SwiftUIX#360]
![image](https://user-images.githubusercontent.com/22151098/158291060-93359d96-38b3-4004-a4fc-b90307319ff1.png)
![image](https://user-images.githubusercontent.com/22151098/158291199-9c68829b-a49a-4205-86f3-395e8a33a715.png)

**Comment by vmanot** [comment]
@BugMonkey this is now fixed.
