### ISSUE TITLE
Missing argument for parameter 'rootView' in call

### ISSUE THREAD

**Issue by NickBrinsmade** [SwiftUIX/SwiftUIX#369]
Getting this error in AppKitOrUIKitViewLifecycleEvent.swift file. Not sure exactly what could be causing this error as it seems to be Xcode version/build related. I was operating with Xcode 12.5.* and everything was working fine. When I updated my Xcode (to 13.2.1), my project started throwing this error in the UIViewControllerType initialization. Not sure how to fix, any advice is much appreciated.

```
func makeUIViewController(context: Context) -> UIViewControllerType {
        UIViewControllerType() //Missing argument for parameter 'rootView' in call.
}
```
I'm thinking it might have to do with UIViewControllerType conforming to the UIHostingController<Content> protocol:

<img width="567" alt="Screen Shot 2022-05-01 at 10 14 19 PM" src="https://user-images.githubusercontent.com/53922149/166176561-7aa8fe28-e9b5-4c5a-9292-d39671bb74fa.png">

As a side note, I also just started getting this error after the update, again--not sure how to fix:

<img width="1171" alt="Screen Shot 2022-05-01 at 10 15 42 PM" src="https://user-images.githubusercontent.com/53922149/166176646-249e240e-5da5-46bc-9fe2-9ac60eb6fc30.png">

Please let me know if there is any specific information I can add to help troubleshoot this.

**Comment by vmanot** [comment]
@NickBrinsmade you're on an extremely old version of SwiftUIX. I'd recommend removing and re-adding the dependency with a flexible constraint of up to the next major version.
