### ISSUE TITLE
Crashed when using isIntialFirstResponder on CocoaTextField

### ISSUE THREAD

**Issue by yosshi4486** [SwiftUIX/SwiftUIX#37]
# Environment
- master branch
- CocoaTextField.swift

# Problem
Crashed when using `isIntialFirstResponder(true)` modifier.

<img width="971" alt="スクリーンショット 2020-03-16 13 31 16" src="https://user-images.githubusercontent.com/9734876/76731100-f2d92700-679f-11ea-84b0-73d9003aa0a2.png">
eg)

```swift
SomeView
.sheet(isPresented: $isPresented) {
    CocoaTextField("", text: self.$text)
        .isInitialFirstResponder(true)
}
```

# Why
Calling `becomeFirstResponder() -> Bool` may cause crash before adding the view to view hierarchy as described in this apple document.: (https://developer.apple.com/documentation/uikit/uiresponder/1621113-becomefirstresponder)

I suppose SwiftUI doesn't change view hierarchy while it is in `makeUIView` step. so,  Calling `becomeFirstResponder()` in `makeUIView` cause crash.

# Workaround
Use `DispatchQueue.main.async` to delay executing `becomeFirstResponder()`. `updateUIView()` doesn't occur crash, so I suppose SwiftUI add view to view hierarchy just after `makeUIView()`.

## before
```swift
public func makeUIView(context: Context) -> UIViewType {
        let uiView = _UITextField()
        
        uiView.delegate = context.coordinator
        
        if let isFirstResponder = isInitialFirstResponder, isFirstResponder {
                uiView.becomeFirstResponder()
        }
        
        return uiView
    }
```

## after
```swift
public func makeUIView(context: Context) -> UIViewType {
        let uiView = _UITextField()
        
        uiView.delegate = context.coordinator
        
        if let isFirstResponder = isInitialFirstResponder, isFirstResponder {
            
            DispatchQueue.main.async {
                uiView.becomeFirstResponder()
            }
        }
        
        return uiView
    }

```

**Comment by vmanot** [comment]
Fixed! Thank you for reporting. It's weird because I haven't encountered this on iOS 13.4, but I know that SwiftUI is buggy across older versions.
