### ISSUE TITLE
Tap Action of Button is not recognized when it is shown inside windowOverlay

### ISSUE THREAD

**Issue by ParthaGudivada** [SwiftUIX/SwiftUIX#370]
If I show a group of views inside a list and if a button is shown using `windowOverlay` modifier,  then the tap action on the button is not recognized.  However if the same of group of views are presented inside a ScrollView, then the tap action on the button is recognized.  

Following is a trivial example.

1.  `ContentView`  shows the cards either in a `ScrollView` or using `List` (in the shown example, I commented out the ScrollView and the cards are presented using the List)
2.   `ShowButtonsView` has the button which can be tapped
3.   For this example the first Card with text message `Card 0` is alone tappable.  Upon tapping the `Card 0`, it presents the button `Tap Me` which can be tapped.

```Swift
struct ContentView: View {
	
	@State private var toggleVisible = false
	
	var body: some View {
		
		//ScrollView {                                 // <-- if it is part of scrollView, tap action of the button shown in ShowButtonsView is recognized
		List {                                               // <-- if it is part of List, tap action action of the button shown in ShowButtonsView is not recognized
			ForEach((0...5), id: \.self) { token in
				
				CardView(tokenNum: token)
					.frame(height: 300)
					.onTapGesture {
						guard token == 0 else { return }
						toggleVisible.toggle()
					}
					.windowOverlay(isKeyAndVisible: $toggleVisible) {
						
						ShowButtonsView()
							.padding()
							.frame(width: 100, height: 40)
							.background(Color.orange)
					}
					.padding(.vertical)
				
				
			}
		}
		
	}
}

```

```Swift
struct CardView: View {
	
	let tokenNum: Int
	
	var body: some View {
		
		VStack {
			Spacer()
			HStack {
				Spacer()
				Text("Card \(tokenNum)")
				Spacer()
			}
			Spacer()
		}
		.background(Color.gray)
		.cornerRadius(10)
		.padding(.horizontal)
		
	}
}
````

```Swift


struct ShowButtonsView: View {
	var body: some View {
		VStack {
			Button {
				print("I am tapped")
			} label: {
				Text("Tap Me")
					.foregroundColor(.red)
			}

		}
	}
}

```

Thanks for sharing a great library

**Comment by vmanot** [comment]
I can't seem to repro this anymore - closing as an Apple bug, please reopen if it persists.
