### ISSUE TITLE
ImagePikcer: When click 'Cancel' Button,ImagePicker cannot dismiss itself.

### ISSUE THREAD

**Issue by NNWJH** [SwiftUIX/SwiftUIX#371]
after onCancel(),should call dismiss function.

**Comment by Overcot** [comment]
I guess the idea is that you don't always need to automatically dismiss view if `cancel` is tapped. Maybe you should dismiss ImagePicker by yourself if you are using custom onCancel closure?

**Comment by vmanot** [comment]
@NNWJH this is by design, you should dismiss the `ImagePicker` by resetting its presentation binding.
