### ISSUE TITLE
Error: Ambiguity when creating list sections

### ISSUE THREAD

**Issue by EvanCooper9** [SwiftUIX/SwiftUIX#372]
The extension to `Section` at [/Sources/Intermodular/Extensions/SwiftUI/Section++.swift](https://github.com/SwiftUIX/SwiftUIX/blob/fe9fca48bdeb5fdaa8bd15112407e656c6094ac9/Sources/Intermodular/Extensions/SwiftUI/Section%2B%2B.swift#L22-L30) causes ambiguity.

> Ambiguous use of 'init(content:header:footer:)'

Commenting out this particular method unblocks me, but I'd rather not maintain a local copy of this package. I'm happy to open a PR that deletes this method, but am unaware of possible side effects throughout the codebase.

Here's a simple example that reproduces the issue:
```swift
import SwiftUI
import SwiftUIX

struct Example: View {
    var body: some View {
        Section { // Ambiguous use of 'init(content:header:footer:)'
            Text("Content")
        } header: {
            Text("Header")
        } footer: {
            Text("Footer")
        }
    }
}
```

**Comment by Overcot** [comment]
<img width="906" alt="Screenshot 2022-05-09 at 14 01 26" src="https://user-images.githubusercontent.com/13967242/167397017-4e65acfe-9eac-43de-a0e2-328165b3cc9d.png">
I guess the library method is no longer required

**Comment by vmanot** [comment]
@EvanCooper9 @Overcot yeah I should just get rid of this, will investigate if that breaks any code but I'll fix this one in the upcoming release.

**Comment by vmanot** [comment]
This is now fixed on `master`.

**Comment by EvanCooper9** [comment]
Thank you!
