### ISSUE TITLE
Bug: Keyboard.dismiss() not working on iOS15

### ISSUE THREAD

**Issue by JulesMoorhouse** [SwiftUIX/SwiftUIX#375]
Hey,

I've just been trying `Keyboard.dissmiss()` on an iOS 15 device and it doesn't hide the keypad.

I guess it could be my implementation.

But I just thought I'd ask if there might be any problems?

Thanks,

Jules.

**Comment by vmanot** [comment]
@JulesMoorhouse it seems to work for me, would its be possible for you to demo a repro?

**Comment by JulesMoorhouse** [comment]
Unfortunately I’m no longer working on this project and cannot produce some repro code.

However, thanks

**Comment by vmanot** [comment]
@JulesMoorhouse feel free to reopen if you encounter it again in the future.
