### ISSUE TITLE
CocoaScrollView continue to bounce even after setting scrollBounceDisabled(true)

### ISSUE THREAD

**Issue by Saik0s** [SwiftUIX/SwiftUIX#377]
First of all, thank you for this excellent library! It gave me a lot of ideas and saved a ton of time.

I was trying to disable horizontal bounce on `CocoaScrollView` using `alwaysBounceHorizontal` and `scrollBounceDisabled`, and it didn't work. The only way to disable bounce that I found is to use `CocoaScrollViewReader` and directly set `proxy.underlyingAppKitOrUIKitScrollView?.bounces = false`, which is, of course, far from ideal. Am I missing something?

Disabling bounce was the main reason for switching from `SwiftUI.ScrollView` with Introspect to `CocoaScrollView`. Can `UIScrollView.bounces` be exposed through `CocoaScrollViewConfiguration`?

**Comment by vmanot** [comment]
@Saik0s this smells like a bug, I'll investigate.

**Comment by sammycooks999** [comment]
I'm noticing a lot of issues with cocoa related aspects of the library. Perhaps a helper framework could be created? @vmanot
