### ISSUE TITLE
How to link this as the static framework(or library) with SPM?

### ISSUE THREAD

**Issue by jegumhon** [SwiftUIX/SwiftUIX#382]
First, this is really nice & useful for me to develop with SwiftUI through SPM! Thank you for creating!!!!

Well, recently I've been trying to use the Xcode cloud(it's on the Beta status, though). 
Then, there is one trouble to link the SwiftUIX. It's below.

> ITMS-90334: Invalid Code Signature Identifier. The identifier "SwiftUIX-555549447bbe021b6ee9380b9449410974d4a8e1" in your code signature for "SwiftUIX_-28E34FF57BD7AEF5_PackageProduct" must match its Bundle Identifier "SwiftUIX".

Since I found out, the issue seems to be from linking the dynamic framework. It occurs,  even though, the SwiftUIX doesn't have the `type` property as `dynamic`.
(This is talking about the Package.swift's setting properties)

So, I'd like to know how to use the SwiftUIX as the static framework through SPM.
Because they're linked as the static framework, even though some other frameworks(ex. Alamofire) doesn't have any settings for this, through SPM. Is there any specific options using frameworks or libraries through SPM?

I've had one thing to resolve this. It's the SwiftUIX target's `MACH_O_TYPE` property sets the `static library`. 
It's useful & effective to avoid the trouble. So, I'm preparing the P.R for it. But, I think there could be the other awesome resolution.
So, I'd like to ask a question like this title.
Could anyone help or give an advice for this?

**Comment by vmanot** [comment]
Hey - I'm not sure if this is a SwiftUIX issue or an SPM issue - there's nothing in the package manifest marking it explicitly as a dynamic library. I'd recommend filing a DTS and reaching out to Apple about this, closing this for now as out-of-scope.
