### ISSUE TITLE
navigationBarItems trailing background is not clear

### ISSUE THREAD

**Issue by hstdt** [SwiftUIX/SwiftUIX#384]
iOS 13.3

```
$0.navigationBarItems(center: Text(""), trailing: trailing, displayMode: .inline)
```

![CleanShot 2022-08-02 at 12 08 00](https://user-images.githubusercontent.com/10215098/182289735-c57fc208-de0c-4cb4-bdc2-5c3142df2c35.png)

`viewDidLoad` in `_ContentHostingController` is not called in iOS 13,  but works fine in iOS 15

![CleanShot 2022-08-02 at 12 06 13](https://user-images.githubusercontent.com/10215098/182289580-a49595d1-7c70-4a14-a8ca-65b44d2ac102.png)

**Comment by vmanot** [comment]
@hstdt can you update to the tip of `master` and see if this is fixed for you now?

**Comment by hstdt** [comment]
> @hstdt can you update to the tip of `master` and see if this is fixed for you now?

Thank you, it's fixed!
