### ISSUE TITLE
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by CoderJohnhao** [SwiftUIX/SwiftUIX#385]
![image](https://user-images.githubusercontent.com/18332430/183003443-287dc8c3-34a5-470c-aa06-5037ed7129e7.png)

**Comment by CoderJohnhao** [comment]
ios 13.0 crashes

**Comment by vmanot** [comment]
@CoderJohnhao iOS 13.0 shipped a very broken version of SwiftUI, I'm almost inclined to drop support for 13 altogether since supporting it across 13-16 is starting to look infeasible.
