### ISSUE TITLE
CocoaHostingController not working 

### ISSUE THREAD

**Issue by beachcitiessoftware** [SwiftUIX/SwiftUIX#386]
In SceneDelegate:

`window.rootViewController = CocoaHostingController(mainView: contentView)`

In first view:
```
@Environment(\.presenter) var presenter
...    
.onAppear {
  if let presenter = presenter {
      presenter.present(EmptyView())
  }
...
```

presenter is always nil. 

What am I missing?  This should work according to the Wiki?  https://github.com/SwiftUIX/SwiftUIX/wiki/Dynamic-Presentation

**Comment by vmanot** [comment]
@beachcitiessoftware this is odd, I'll take a look into it.
