### ISSUE TITLE
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

### ISSUE THREAD

**Issue by danqing** [SwiftUIX/SwiftUIX#387]
Getting this error since updating to Xcode 14 / iOS 16. This is in the `ReferenceBox` file.

<img width="1189" alt="CleanShot 2022-09-15 at 21 21 57@2x" src="https://user-images.githubusercontent.com/5134133/190536257-5caeeb1b-a7a7-4ad1-b875-65ac067df7be.png">

**Comment by vmanot** [comment]
@danqing this is fixed on `master`.
