### ISSUE TITLE
General UIHostingView Question

### ISSUE THREAD

**Issue by NicholasBellucci** [SwiftUIX/SwiftUIX#391]
I have recently been trying to figure out the best way to add SwiftUI views to UIViews and stumbled across SwiftUIX UIHostingView. Looking through the implementation everything makes sense on how it is implemented and works overall. One question I have though is if it is a big issue that the underlying UIHostingController is not going to be added as a child to the view controller that the view resides in? From what I have tested and can tell it doesn't seem like an issue but maybe I am missing an edge case or something.

**Comment by vmanot** [comment]
@NicholasBellucci adding it automatically ended up causing issues (I don't recall the specifics unfortunately, may have changed with iOS 16). Since it's worked fine like this for most use cases I've just decided to keep it that way.

**Comment by NicholasBellucci** [comment]
That makes complete sense. Thanks for more insight!
