### ISSUE TITLE
inputAccessoryView on ios14 will enlarge the inputAccessoryView for long

### ISSUE THREAD

**Issue by xulidegitHub** [SwiftUIX/SwiftUIX#396]
$0.inputAccessoryView({
            VStack(alignment: .trailing) {
              HStack(alignment: .center) {
                Spacer()
                Button {
                  isEditing = false
                  onCommit(text ?? "")
                } label: {
                  Text("完成")
                    .foregroundColor(.blue)
                    .font(.system(size: 14))
                }
                .padding(.trailing)
              }
            }
          })
        })
![image](https://user-images.githubusercontent.com/16676652/196594432-f9bf08db-a18f-4eb2-937c-6df5d6209dcd.png)

**Comment by vmanot** [comment]
@xulidegitHub I may deprecate this API, have not been able to find a reliable workaround.

**Comment by vmanot** [comment]
This should be fixed now.
