### ISSUE TITLE
SwiftUI Font to Cocoa Font conversion

### ISSUE THREAD

**Issue by maximkrouk** [SwiftUIX/SwiftUIX#400]
Hi there, just implemented a working custom conversion to UIKit.Font using a reflection (iOS 14+)
https://gist.github.com/maximkrouk/e8c2c362715756077e6382ffa0e4ea59

Maybe it can be improved using some caching like u did with colors, but at least it can convert custom fonts

**Comment by vmanot** [comment]
@maximkrouk I'll take a look into integrating this, thanks!

**Comment by vmanot** [comment]
@maximkrouk this has been integrated as `Font.toAppKitOrUIKitFont()`.
