### ISSUE TITLE
SwitchOver disappeared

### ISSUE THREAD

**Issue by ggruen** [SwiftUIX/SwiftUIX#401]
Looks like `SwitchOver` was removed in commit [73805](https://github.com/SwiftUIX/SwiftUIX/commit/738057f2248af8c4e62683fde3a9784a0857e277), which is ironically labeled "Get rid of half-baked APIs/unused code". (Ironic, because I'm using it in my production app :) ).

Can we bring it back, or do you have a replacement suggestion for it?

**Comment by vmanot** [comment]
Hey @ggruen, apologies for the breaking change and addressing this so late! 

`SwitchOver` is back - thank you for raising the issue. I honestly did not think anyone was using it, but that's on me haha. 

I'd recommend switching over to `@ViewBuilder` if possible, `SwitchOver` and `UnwrapOptionalView` were written at a time when [result builders](https://www.swiftbysundell.com/articles/deep-dive-into-swift-function-builders/) were still being fledged out and did not support `switch` statements. 

I'm going to review the `SwitchOver` API again closely, and mark it as deprecated it if I think that result builders have fully subsumed it.
