### ISSUE TITLE
How to set `isPagingEnabled` for `CollectionView`?

### ISSUE THREAD

**Issue by denandreychuk** [SwiftUIX/SwiftUIX#402]
I am implementing the custom collection view layout UPCarouselFlowLayout, which relies on paging, and I wish to enable it.

**Comment by vmanot** [comment]
@denandreychuk pagination with SwiftUIX's `CollectionView` is currently out of scope. I do want to offer it at some point, but I don't see it being worked upon anytime soon. Am closing this issue for now, but if this is something that is important enough that you'd like to tackle it yourself am happy to guide on high level steps.
