### ISSUE TITLE
installing in xcode 14?

### ISSUE THREAD

**Issue by willwade** [SwiftUIX/SwiftUIX#407]
Call me stupid - but how do I install this now in xcode 14? the readme doesn't work

**Comment by vmanot** [comment]
@willwade hmm, the [installation guide](https://github.com/SwiftUIX/SwiftUIX#installation) should still be relevant for Xcode 14. Have you tried the steps mentioned there?

**Comment by willwade** [comment]
Yeah. I think it's because Xcode has changed the way packages are organised

Eg. "File → Swift Packages → Add Package Dependency..."

I can't see that. Am I being stupid though?! Possibly!

**Comment by vmanot** [comment]
@willwade I think [this tutorial](https://cocoacasts.com/xcode-fundamentals-how-to-add-a-swift-package-to-a-project) by @bartjacobs should be helpful, let me know if it resolves your issue?

**Comment by vmanot** [comment]
@willwade am closing this issue, feel free to reopen if it persists.
