### ISSUE TITLE
Would it be possible to have a feature to show the colorpicker on a cell tap instead of have to press the small colorwell button as i find it too small and can never hit it correctly

### ISSUE THREAD

**Issue by atebitsy** [SwiftUIX/SwiftUIX#408]
Would it be possible to have a feature to show the default UIColorPicker on a cell tap instead of have to press the small colorwell button as i find it too small and can never hit it first time and it’s incredibly frustrating, i’d be happy to donate to have a feature like this.

**Comment by vmanot** [comment]
Hi @atebitsy, I'm not taking on sponsored feature requests at the moment - but I'll leave this issue open and mark it as "help wanted" in case someone else wants to take it on :)

**Comment by atebitsy** [comment]
> Hi @atebitsy, I'm not taking on sponsored feature requests at the moment - but I'll leave this issue open and mark it as "help wanted" in case someone else wants to take it on :)

Thank you I appreciate that, I love your work btw 🤗
