### ISSUE TITLE
[Bug] Not correctly reload button in navigation bar

### ISSUE THREAD

**Issue by lfongaroScp** [SwiftUIX/SwiftUIX#41]
Hi,
I use your library. Thanks for your work.
I have a problem.
In my app I set the bar ButtonItems like this
```
NavigationView {
MyView(vM: .init()).navigationBarItems(leading: self.LeadingButton(), center: self.NavbarImage(),
                                                            trailing: self.TrailingButton(), displayMode: .inline)
}
```

However, sometimes I need to hide/modify the barbuttons I show to the user.
So, there is a @Published variable in the model of the Main View that change if the user make specific action.

Here the problem:
the buttons are not update, it still show the old ones.
I try to use the native method of SwiftUI (without center and displayMode) and it works fine the buttons update, so I guess the problem is a missing refresh. What can I do?

**Comment by vmanot** [comment]
Taking a look at this. Which version of iOS are you on?

**Comment by lfongaroScp** [comment]
Hi,
Thanks for the reply. I have an iPhone7 with iOS 13.3.1
And XCode 11.3.1

**Comment by lfongaroScp** [comment]
Hi, 
I search a bit in your code:
I guess the problem is these istruction:

Row 62, NavigationBarConfigurator.swift
```
if let leading = leading {
                if !(leading is EmptyView) {
                    if parent.navigationItem.leftBarButtonItem == nil {
                        parent.navigationItem.leftBarButtonItem = .init(customView: UIHostingView(rootView: leading))
                    } else if let view = parent.navigationItem.leftBarButtonItem?.customView as? UIHostingView<Leading> {
                        view.rootView = leading
                    } else {
                        parent.navigationItem.leftBarButtonItem?.customView = UIHostingView(rootView: leading)
                    }
                }
            }
```

I put a couple of breakpoint. When I update the icons it trigger the "else if" condition.
Then I try this:
first instantiate only the center and trailing icons (leading is left empty)
Then update the icons leading, center and trailing.
The leading icons will be update, the other two no.

**Comment by vmanot** [comment]
This should be fixed now.
