### ISSUE TITLE
Call action when the first page dragged to right.

### ISSUE THREAD

**Issue by kelalaka153** [SwiftUIX/SwiftUIX#412]
Is it possible to call an action when the first page dragged to right? Currently the page stays.

I want to close the view with this action. As far as I can see there is no hook to achieve that? Is there a way for this?

**Comment by vmanot** [comment]
@kelalaka153 not at the moment. I do want to build a proper API for interactive scrolling, but just don't have the bandwidth at the moment. Am closing this as out of scope for now.
