### ISSUE TITLE
TakeSnapshotView does not work as expected

### ISSUE THREAD

**Issue by denandreychuk** [SwiftUIX/SwiftUIX#414]
I am experiencing several issues with the TakeSnapshotView:

1. AttributeGraph Cycle Detection
`=== AttributeGraph: cycle detected through attribute 33664 ===`

2. State Modification During View Update (Xcode 14+). 
In the new Xcode version (Xcode 14+), the line image.wrappedValue = newImage in TakeSnapshotView causes the following error:
`Modifying state during view update, this will cause undefined behavior.`

4. Intrinsic Size Propagation: 
The TakeSnapshotView does not propagate the intrinsic size correctly. To clarify, consider the following view hierarchy:

 ```
 GeometryReader { proxy in
      ScrollView(showsIndicators: false) {
          Text("Some long\n random text").screenshotOnAppear(to: $captureImage)
              .fixedVerticalSize()
          
          Color.red.height(100)
      }
}
```

In this case, I want the Text view to propagate its size to the ScrollView.

<img width="1280" alt="Screenshot 2023-04-12 at 17 33 48" src="https://user-images.githubusercontent.com/32373518/231491097-3f0f39b2-0454-4dda-98d3-07556c8677f9.png">

**Comment by vmanot** [comment]
@denandreychuk can you upload an encapsulated project I can run to reproduce this? I'm low on bandwidth, doing so would help me debug + close this issue faster.

**Comment by denandreychuk** [comment]
@vmanot sure!
Hope this helps
https://github.com/denandreychuk/TakeSnapshotViewIssue

**Comment by denandreychuk** [comment]
Also it would be really nice, if we could capture a screenshot of the view that isn't visually displayed on the screen.

**Comment by vmanot** [comment]
@denandreychuk I think I've fixed the runtime warning. I don't have the bandwidth to investigate + fix the height issue atm, but one good place to start could be conditionally using `ImageRenderer` on iOS 16 to mitigate it.

**Comment by denandreychuk** [comment]
Hey @vmanot,

Thanks for the quick fix on my issue! You rock! 🚀

I'll be able to check the updates to TakeSnapshotView in a few days and investigate the height issue. If I find a solution, w8 for a PR :)

**Comment by vmanot** [comment]
Closing this for now as it's been inactive for a bit, please feel free to reopen if there's an update.
