### ISSUE TITLE
CocoaTextField Failed to produce diagnostic for expression in ExtractedView

### ISSUE THREAD

**Issue by hapton** [SwiftUIX/SwiftUIX#416]
> import SwiftUI

import SwiftUIX

struct SDMRegisterInputView: View {
    @Binding var fieldValue: String
    @Binding var isFocus: Bool

    var body: some View {
        
        VStack{
            CocoaTextField("", text: $fieldValue, isEditing: $isFocus).font(font).focused($isFocus).foregroundColor(UIColor(0x181E25)).textContentType(.emailAddress).padding(.leading, 16)
        }
        
      
    }
}

struct SDMRegisterInputView_Previews: PreviewProvider {
    static var previews: some View {
        SDMRegisterInputView(fieldValue: Binding.constant("ss"), isFocus: Binding.constant(false))
    }
}
CocoaTextField will produce a error in an ExtractedView.Error description is "Failed to produce diagnostic for expression; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project".
Dev tools: XCode 14.2 Apple M1

**Comment by hapton** [comment]
The reason may be font is not defined

**Comment by vmanot** [comment]
@hapton I'm closing this because it seems like a Swift compiler diagnostics issue. I've run into this issue myself (with/without SwiftUIX involved). Feel free to reopen if it's something the SwiftUIX codebase can be tweaked to fix.
