### ISSUE TITLE
PaginationView overlap issue

### ISSUE THREAD

**Issue by okcoker** [SwiftUIX/SwiftUIX#417]
Left this comment on a [closed ticket](https://github.com/SwiftUIX/SwiftUIX/issues/204#issuecomment-1515854111) but maybe it should be it's own issue.

I'm running into an overlap issue with other views seemingly ending up underneath the PaginationView.

Here's a minimal project example. You'll notice it can take several clicks on the "Skip" button to recognize the tap

[paginationviewoverlap.zip](https://github.com/SwiftUIX/SwiftUIX/files/11283528/paginationviewoverlap.zip)

**Comment by sthahemant1st** [comment]
I just downloaded and run your project I didn't find any issue where Button not being tapped. Actually only text of your button is tappable which may be your issue. 
```
HStack {
                    Button(
                        action: {
                            currentPageIndex = 2
                        },
                        label: {
                            Text("Skip")
                            .font(.system(size: 14, weight: .semibold, design: .rounded))
                            .foregroundColor(Color.gray)
                            .padding(skipButtonPadding)
                            .border(Color.green, width: 1)
                            .hidden(currentPageIndex == 2)
                        }
                    )
                    Spacer()
                    Button(
                        action: {
                            currentPageIndex += 1
                        },
                        label: {
                            Text("Next")
                                .padding(skipButtonPadding)
                                .border(Color.green, width: 1)
                                .hidden(currentPageIndex == 2)
                        }
                    )
                    
                }
```

**Comment by okcoker** [comment]
@sthahemant1st did you happen to try on a physical device? On the simulator it worked for me, but not on my iphone x (i believe it was with ios 15)

I'm out of an iphone at the moment so I can't give you the exact specs. I'm waiting for the new iphone to come out to retest again.

**Comment by okcoker** [comment]
> Actually only text of your button is tappable which may be your issue.
@sthahemant1st i think you're right here.

Using the `label` argument and sizing the text explicitly seems to work a little better. Tested on  iphone 15 pro max ios 17.0.2. Closing for now
