### ISSUE TITLE
[Bug] NavigationBar size at start

### ISSUE THREAD

**Issue by lfongaroScp** [SwiftUIX/SwiftUIX#42]
Hi,

I have a simple problem: my app when start the navigation bar has the wrong size (expanded and not inline), after a simple refresh the navigationBar change to the correct size, but it is pretty ugly.
If i put an empty navigationTitle the size is correct, but it seems a bit hackish (or maybe is the correct way? I am not very skilled about SwiftUI)
Here a snippet to show what I mean:
```
MyView(viewModel:.init())
                       .navigationBarTitle("", displayMode: .inline) //need this line to show as inline at start
                       .navigationBarItems(leading: EmptyView(), center: NavbarLogoImage(),
                                                          trailing: EmptyView(), displayMode: .inline)
```

**Comment by vmanot** [comment]
@lfongaroScp I've faced this same issue, it seems to be a SwiftUI bug :/
