### ISSUE TITLE
Carousel Effect

### ISSUE THREAD

**Issue by denandreychuk** [SwiftUIX/SwiftUIX#421]
I know that this might not directly pertain to the main focus of SwiftUIX, but I'm hoping you could provide some guidance or suggestions.

I'm looking to achieve a classic carousel effect (horizontal scrolling with paging and a sneak peak of the next cell) using the SwiftUIX framework. I remember that we discussed the idea of implementing support of custom layouts for CollectionView in order to integrate libraries like UPCarouselFlowLayout.

If there's a feature within SwiftUIX or a different approach that can help create this effect, I would be grateful for your input. Alternatively, if you could recommend another library or technique to accomplish this goal, your advice would be extremely helpful.

Thank you for your time and for your excellent work on SwiftUIX.

**Comment by vmanot** [comment]
`CollectionView` supports arbitrary `UICollectionViewLayout`s - though the intrinsic sizing API relies on the layout being a subclass of `UICollectionViewFlowLayout` which is less than ideal. I need to revisit all of it but am completely bandwidth constrained at the moment. If you know the size of your cells beforehand, `CollectionView` with a custom layout may be one viable approach.
