### ISSUE TITLE
navigator always returns nil on iOS13.0,but normal for iOS14.0 and above

### ISSUE THREAD

**Issue by JPSaber** [SwiftUIX/SwiftUIX#426]

**Comment by vmanot** [comment]
@JPSaber I'm going to soft-deprecate support for iOS 13 because of how broken SwiftUI is on it. If you have a fix, feel free to PR, am closing this issue as out of scope for now.

**Comment by JPSaber** [comment]
![image](https://github.com/SwiftUIX/SwiftUIX/assets/20967048/08059c27-541b-4faa-9abd-ac4e8989daec)
The objectWillChange.send() method is problematic in iOS 13.0 because it does not execute the view's body, resulting in the navigator not being initialized
