### ISSUE TITLE
 Implement Pinch to Zoom Feature in CocoaScrollView

### ISSUE THREAD

**Issue by lindezhen** [SwiftUIX/SwiftUIX#430]
I have been using your CocoaScrollView library and have encountered a requirement to implement pinch-to-zoom functionality within the ScrollView. In UIKit, we are able to do this by setting the delegate of the UIScrollView and implementing the respective zoom methods. However, with the current implementation of CocoaScrollView, there seems to be no direct way of accomplishing this.

I believe that this feature would be highly beneficial to many developers using your library. If possible, I would like to request you to consider adding this functionality in a future release. If implementing this feature could cause other issues, or if there's another way to achieve this that I might not have considered, I am open to your suggestions.

Thank you for taking the time to read my suggestion. I look forward to hearing from you.

**Comment by vmanot** [comment]
@lindezhen I'm currently swamped and don't have the bandwidth to take this on, feel free to PR.
