### ISSUE TITLE
optionalEnvironmentObject usage

### ISSUE THREAD

**Issue by andrewsexcellent** [SwiftUIX/SwiftUIX#435]
Hey,

I see that `optionalEnvironmentObject` is now deprecated, but I'm not 100% clear on what replaces it.

Let's say I have:

```
struct ViewA: View {
    @EnvironmentObject.Optional private var optionalEnvObject: OptionalEnvObject?
}
 ```

and then go to initialize it in another view with

```
struct ParentView: View {
 private var optionalObject: OptionalEnvObject?

  var body: some View { 
    ViewA()
      .optionalEnvironmentObject(optionalObject)
  }
}
```

What do I replace `.optionalEnvironmentObject(optionalObject)` with? 
`.environmentObject(optionalObject)` doesn't work.

`.optionalEnvironmentObject(optionalObject)` still works but lets me know that it's deprecated

Thanks!

**Comment by vmanot** [comment]
@andrewsexcellent I'd recommend copying over the code from SwiftUIX and removing the deprecated tag. I'm deprecating it because I'm unsure whether it's going to be stable going forward with iOS 17.
