### ISSUE TITLE
Segmentation Fault 11 on archive using Xcode 11.4

### ISSUE THREAD

**Issue by Brett-Best** [SwiftUIX/SwiftUIX#44]
```swift
import SwiftUIX

struct MyButtonStyle: ButtonStyle {
  func makeBody(configuration: Configuration) -> some View {
    configuration.label
  }
}

struct ContentView: View {

  var body: some View {
    Button("My Button", action: {})
      .buttonStyle(MyButtonStyle())
      .fill()
  }
  
}

struct ContentView_Previews: PreviewProvider {
  static var previews: some View {
    ContentView()
      .fill()
  }
}
```

Using Xcode 11.4, create a blank project (add SPM SwiftUIX) and use the above code snippet for the content view.
Attempt to archive the project for release, a segmentation fault 11 should be produced.

The following tweets might be helpful, as well as the two commits linked.
https://twitter.com/codeslice/status/1247141849531326465?s=21
https://twitter.com/codeslice/status/1247142251861618695?s=21

Entire thread: https://twitter.com/brettbestaus/status/1242648289742225408?s=20

https://github.com/CodeSlicing/pure-swift-ui/commit/4fb6f2933125c5a558e98736c12690bef4cc18ee
https://github.com/CodeSlicing/pure-swift-ui/commit/0a242ffbd140c7dd9259de558bfbece8c13dfc7a

**Comment by vmanot** [comment]
Thank you for reporting this! The links were extremely helpful, and I've resolved the archive issues with the provided example.

**Comment by vmanot** [comment]
Leaving this issue open to track further segfaults - looks like this is going to be a rough ride till 11.4.1 is released and hopefully fixes the compiler bug(s).

**Comment by Brett-Best** [comment]
Thanks for the quick fix, glad the links were helpful (:

**Comment by vmanot** [comment]
@Brett-Best most of the issues should be fixed now, after a thorough sprinkling `@inlinable` and `@usableFromInline` all across the project. Feel free to raise a new one if anything comes up!
