### ISSUE TITLE
How to use .toolbar with  .windowOverlay

### ISSUE THREAD

**Issue by iAllenC** [SwiftUIX/SwiftUIX#445]
on mac, I wrote code like:
`
.windowOverlay {
    SomeView()
        .toolBar {
            SomeToolBar()
        }
}
`
but the toolbar was added into the main window instead of the overlaid window. Is there a method to make the toolbar to be added into the overlaid window?

**Comment by vmanot** [comment]
@iAllenC unfortunately, interop with SwiftUI's toolbar APIs are out of scope. I've looked into this, I don't think there's a way to hook into SwiftUI's runtime to ensure that `.toolbar` selects a custom `NSWindow`.
