### ISSUE TITLE
Crash on Dynamic Presentation Demo Example

### ISSUE THREAD

**Issue by skywalkerlw** [SwiftUIX/SwiftUIX#447]
I used the demo example from `https://github.com/SwiftUIX/SwiftUIX/wiki/Dynamic-Presentation#problem` and it simply crashes in XCode 14.3

**Comment by vmanot** [comment]
@skywalkerlw that guide was for when SwiftUI didn't have a native app lifecycle (it notes that your root view controller must be a `CocoaHostingController`, SwiftUIX's `UIHostingController` subclass. I'll update it soon.
