### ISSUE TITLE
Support visionOS

### ISSUE THREAD

**Issue by vmanot** [SwiftUIX/SwiftUIX#448]

**Comment by vmanot** [comment]
It was technically supported until Apple flip-flopped on the decision to translate `#if os(iOS)` to effectively include `os(xrOS)`.

I don't want to explicitly use `#if os(xrOS)` on `master` because it generates a compiler warning on Xcode 14 (since it doesn't know about `xrOS`).

Given that the RC is just a week away, I'm inclined to make a stable release for SwiftUIX on Xcode 14, and then soft-drop (i.e. be okay with the compiler warnings for `xrOS`) Xcode 14 support altogether.

**Comment by denandreychuk** [comment]
any progress on this?

wdyt about different branch with support for visionOS which will be merged later?

**Comment by vmanot** [comment]
@denandreychuk I'm working on fixing this in the next couple of days.

**Comment by vmanot** [comment]
@denandreychuk currently very constrained on bandwidth, which is why this is dragging on. If you'd like to contribute that'd be very much appreciated.

**Comment by denandreychuk** [comment]
its okay @vmanot

Do you have any recommendations for visionOS support implementation? I mean something that I should be aware of.

**Comment by vmanot** [comment]
@denandreychuk done, lmk if you run into any issues.
