### ISSUE TITLE
CocoaScrollView Can't Handle LazyHStack / LazyVStack.

### ISSUE THREAD

**Issue by nuhash-bcraft** [SwiftUIX/SwiftUIX#450]
I have used this code to investigate if lazy property works. But Lazy characteristic doesn't work inside CocoaScrollView . All the views inside Lazy Block is rendered at once, causing memory issue handling large quantity of data.
```
CocoaScrollView(.horizontal){
            LazyHStack(spacing: 10){
                ForEach(1..<100, id: \.self) { id in
                    Text("HELLO")
                        .frame(width: 60, height: 60)
                        .onAppear(perform: {
                            print("Appeared")
                        })
                    
                }
            }
        }

**Comment by vmanot** [comment]
@nuhash-bcraft this is a known issue - unfortunately I'm not aware of any public (or even undocumented) SwiftUI APIs that allow me to replicate the internal coordination between `LazyVStack` and SwiftUI's `ScrollView`.

**Comment by nuhash-bcraft** [comment]
Thank You for your Updated and prompt reply.

**Comment by xuanyuelin** [comment]
Is there any solution till now, I have the same problem

**Comment by nuhash-bcraft** [comment]
No solution Found, Still Struggling. :)

**Comment by xuanyuelin** [comment]
Maybe I found a trick way to solve this. Add a native scrollview inside the cocoaScrollView to load the danamiclly rendered contents

**Comment by vmanot** [comment]
@xuanyuelin if that works, let me know I can add a modifier to `CocoaScrollView` to adopt this hack as an unsafe flag.

**Comment by xuanyuelin** [comment]
It does not work. The compiler build failed if your embed a scrollview into another. It totally different with UIKit.

**Comment by vmanot** [comment]
@xuanyuelin this is entirely in Apple's hands. If they open up ways for me to interact with lazy content, I'll implement it. `UIHostingController` and `NSHostingController`'s public methods force evaluation non-lazily, I don't know how SwiftUI is implementing it internally.
