### ISSUE TITLE
Setting `SearchBar` `isEditing` binding value to `false` doesn't defocus search bar

### ISSUE THREAD

**Issue by Sjmarf** [SwiftUIX/SwiftUIX#451]
I'm using this on iOS 17:

```py
            .navigationSearchBar {
                SearchBar("Search", text: $searchText, isEditing: $isSearching)
                    .showsCancelButton(page != .home)
                    .onCancel {
                        page = .home
                    }
                    
                }
            .navigationSearchBarHiddenWhenScrolling(page != .home)
```

Setting `isSearching` to `false` elsewhere in my view doesn't deselect the search bar. I'm looking into using `Keyboard.dismiss` instead, but I expected to be able to do it with the binding. Am I missing something? I tried the `.focused` modifier too, but that didn't work either.

**Comment by vmanot** [comment]
@Sjmarf that's odd - it should defocus it, would it be possible for you to reproduce this in an isolated Xcode project that I can test?

**Comment by Sjmarf** [comment]
Sure. Let me know if I'm doing something wrong. I'm using XCode 15 on an iOS 17 sim.

https://github.com/Sjmarf/SwiftUIXSearch

**Comment by vmanot** [comment]
@Sjmarf I think your repo might be private - the link leads to a 404 for me 😅

**Comment by Sjmarf** [comment]
> @Sjmarf I think your repo might be private - the link leads to a 404 for me 😅 

My apologies, I forgot to make it public. It should work now 👍

**Comment by vmanot** [comment]
@Sjmarf this should be fixed on `master` now.

**Comment by Sjmarf** [comment]
Great, thank you!
