### ISSUE TITLE
TextView .font not working

### ISSUE THREAD

**Issue by hyouuu** [SwiftUIX/SwiftUIX#455]
Setting the font this way doesn't work - it still shows super small fonts. It was working when I was on an earlier version of SwiftUIX back in March
```
TextView(
                    "",
                    text: $text,
                    onEditingChanged: { didChange in
                        print("TextView onEditingChanged")
                    }, onCommit: {
                        print("TextView onCommit")
                    }
                )
                .font(.system(size: 30))
```

**Comment by hyouuu** [comment]
cc @vmanot

**Comment by vmanot** [comment]
Does using `UIFont`/`NSFont` work as a temporary workaround?

**Comment by hyouuu** [comment]
How to use it that way?

**Comment by vmanot** [comment]
@hyouuu pass it to `.font` on `TextView`, it accepts both `Font` and `UIFont`/`NSFont`.

**Comment by hyouuu** [comment]
Ah yea it works - thanks for the workaround!
