### ISSUE TITLE
NavigationBarItems heads up

### ISSUE THREAD

**Issue by smaldd14** [SwiftUIX/SwiftUIX#461]
Hey guys, I've been using SwiftUIX for awhile and wanted to give you all a heads up of a problem I've had that I have recently solved...
Here is my use case:
```
struct ContentView: View {
    var body: some View {
       NavigationView {
          View1()
       }
    }
}

struct View1: View {
   var body: some View {
      VStack {
         NavigationLink(destination: View2()) {
            Text("Hello View 1")
         }
      }.navigationBarItems(leading: Text("View1Leading"), center: Text("View1Center"), trailing: Text("View1Trailing"))
   }
}

struct View2: View {
   var body: some View {
      VStack {
            Text("Hello View 2")
         }
      }
/* EmptyView() does NOT remove the Views from the parent navigationbarItem (Text("View1Leading"), Text("View1Trailing") */
      .navigationBarItems(leading: EmptyView() center: Text("View2Center"), trailing: EmptyView()) 
     // .navigationBarItems(leading: Text(""), center: Text("View2Center"), trailing: Text(""))
     /* You can however, do a text view with empty string and that will remove it */
   }
}
```

i have a parent view that renders a leading, center and trailing view for my .navigationBarItems. I've been struggling for a long time because I will click on a button that takes me to the child View2, and I only want to show the center view of the .navigationbBarItems, but `EmptyView()` does not erase the leading and trailing views. You have to explicitly change the View to something other than `EmptyView()` to get rid of the views in the .navigationBarItems.

Hope this helps somebody that comes along this same issue

**Comment by vmanot** [comment]
@smaldd14 thanks for flagging this, this should be fixed on `master` now!
