### ISSUE TITLE
[Privacy Manifest] Implementation

### ISSUE THREAD

**Issue by corentios** [SwiftUIX/SwiftUIX#466]
Hello,

As we approach the upcoming spring and the anticipated implementation of the [Privacy Manifest](https://developer.apple.com/support/third-party-SDK-requirements/) by Apple, it's crucial to ensure that your SDK fully complies with Apple's requirements.

Does your SDK need to include it?
If so, do you have a release date planned?

Thank you in advance for your attention to this matter.

Best regards

**Comment by alexanderkhitev** [comment]
Thank you @corentios for raising this question.

**Comment by vmanot** [comment]
Thanks for raising this issue @corentios. 

I just read through the linked article. 

>The following are commonly used SDKs in apps on the App Store. Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update.

The reference list does not seem to include SwiftUIX, therefore my understanding is that it does not apply to SwiftUIX. However, if that should change in the future, please reopen this issue/create a new one and I'll resolve it ASAP.

**Comment by corentios** [comment]
Hello @vmanot

Indeed, I see that the article only talks about the SDKs listed, but I have the impression that it's not clear, I've since searched and I came across the answer from an Apple engineer,

What do you think?

"What happens with SDK's that are not in this list? Should every single SDK an app uses to include the privacy manifest file?"

- "Any app and third party SDK that collects data, uses required reason API, or both must include a privacy manifest file. If your app uses an SDK not listed but that falls under the mentioned requirements, then this SDK must include a privacy manifest."



Source : https://forums.developer.apple.com/forums/thread/743295?answerId=776587022#776587022

**Comment by vmanot** [comment]
@corentios I'm unclear on this myself, it seems that Apple has failed to clearly communicate what they want here. If you believe that this framework needs a Privacy Manifest, feel free to reopen (and/or ideally PR if you have the bandwidth!).
