### ISSUE TITLE
Wrong page size with PaginationView and ComposableArchitecture

### ISSUE THREAD

**Issue by marcuswu0814** [SwiftUIX/SwiftUIX#467]
![demo](https://github.com/SwiftUIX/SwiftUIX/assets/6396757/fffa76d4-0678-4b06-bd63-651a0feeec9e)

This is my [reproduce project](https://github.com/marcuswu0814/TCASwiftUIX).

I'm trying to make a pagination view with TCA and it seems using a different initializer overload and the view content got wrong size. I'm not sure what is the root cause of this. But the page count only one:

![CleanShot 2024-02-02 at 18 21 42@2x](https://github.com/SwiftUIX/SwiftUIX/assets/6396757/d26d81c7-c983-49d1-90e8-976d3f93dd44)

More detail description in my [README](https://github.com/marcuswu0814/TCASwiftUIX/blob/master/README.md) file.  If need any other information, feel free to tell me, thanks for doing great work for this library. 🙏

**Comment by vmanot** [comment]
@marcuswu0814 closing this as I believe your PR was the one that fixed it!
