### ISSUE TITLE
AppKit & UIKit Support

### ISSUE THREAD

**Issue by maximkrouk** [SwiftUIX/SwiftUIX#47]
Take a look at [my implementation](https://gist.github.com/maximkrouk/d38f9ec9ffa9fad4a30e87fab29298ed), maybe you'll find it useful 😎

**Comment by vmanot** [comment]
Looks really interesting! Closing this issue as it's more of a discussion rather than an issue, but have bookmarked your code and will definitely add something inspired by it :)
