### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by easiwriter** [SwiftUIX/SwiftUIX#478]
Suddenly, out of the blue,  I'm getting: 

The package product 'SwiftUIX' cannot be used as a dependency of this target because it uses unsafe build flags.

Using Xcode 15.3

I've tried resetting all the packages.

This is a showstopper.

**Comment by corentios** [comment]
+1, same for us

**Comment by vmanot** [comment]
@easiwriter @corentios I'm on it, I'll have a fix up in a couple of hours.

It's technically an Xcode bug, it doesn't complain if SwiftUIX is used as an implicit dependency.

**Comment by vmanot** [comment]
@easiwriter @corentios I just release 0.2.1 which should fix this.
