### ISSUE TITLE
In visionOS report error: Cannot find type '_SwiftUIX_DropInfo' in scope

### ISSUE THREAD

**Issue by YiLee01** [SwiftUIX/SwiftUIX#492]
In visionOS report error: 
Cannot find type '_SwiftUIX_DropInfo' in scope
Generic struct '_SwiftUIX_AnyDropDelegate' requires that 'DropInfo' conform to '_SwiftUI_DropInfoProtocol'
![Uploading WX20240705-225917@2x.png…]()

**Comment by jackguo709** [comment]
+1

**Comment by vmanot** [comment]
@YiLee01 @jackguo709 this should be fixed on the tip of `master`, can you please check? Also what version of Xcode are you using?

**Comment by vmanot** [comment]
Closing this, feel free to reopen if it persists on the tip of `master`.
