### ISSUE TITLE
When building with Xcode16 Beta4, a crash occurs at self.fakeID = AnyHashable(UUID()) in SwiftUIX/Source/SwiftUIX/Intramodular/Miscellaneous/action/Action.swift.

### ISSUE THREAD

**Issue by bsj-r-nagai** [SwiftUIX/SwiftUIX#499]
When building with Xcode16 Beta4, a crash occurs at self.fakeID = AnyHashable(UUID()) in SwiftUIX/Source/SwiftUIX/Intramodular/Miscellaneous/action/Action.swift.

Error details
Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ff7b80d2ff8)

![スクリーンショット 2024-07-26 20 17 48](https://github.com/user-attachments/assets/2b3a1560-a5c6-4adc-aee7-34c59baacb1a)

**Comment by denandreychuk** [comment]
+1
This is weird bug, but this prevents from launching project at all

**Comment by unkosun** [comment]
me too, I hope this bug can be fixed as soon as possible.

**Comment by denandreychuk** [comment]
This is actually fixed in https://github.com/SwiftUIX/SwiftUIX/commit/4962ccec9de6b1053f67a0e2d3534b13ba4bedae

**Comment by vmanot** [comment]
@bsj-r-nagai this is fixed as pointed out by @denandreychuk.

**Comment by vmanot** [comment]
@bsj-r-nagai I've also just launched `0.2.2`.

**Comment by bsj-r-nagai** [comment]
@vmanot 
Thank you very much.
I've also confirmed that it doesn't crash.
