### ISSUE TITLE
Can't load dynamic data inside PaginationView

### ISSUE THREAD

**Issue by sabina1997** [SwiftUIX/SwiftUIX#50]
I have to display some data from api. This is the code:

```
PaginationView(axis: .horizontal) {

                ForEach(self.banners, id: \.id) { item in
               
URLImage(URL(string:"exampleurl")!)
                    { proxy in
                        proxy.image
                            .resizable()
                    }.frame(width: UIScreen.main.bounds.width - 120, height: 200).aspectRatio(contentMode: .fit)
                        .cornerRadius(15)

                }
                
            }.onAppear(perform: loadData)
```

Everything I put inside foreach, even if I put static data it says **Cannot convert value of type 'ForEach<[Banner], Int, some View>' to closure result type 'Array<Element>'**.
How can I load data with foreach inside PaginationView?

**Comment by vmanot** [comment]
@sabina1997 I just introduced an initializer to support this. Could you check and confirm whether it fits your need?

**Comment by vmanot** [comment]
On a more interesting note - true `ForEach` support is in the works. Right now, `PaginationView` is inefficient in that it requires precomputed views - I'm changing that to support fully dynamic, lazy loading.

**Comment by sabina1997** [comment]
> @sabina1997 I just introduced an initializer to support this. Could you check and confirm whether it fits your need?

Show an example please

**Comment by vmanot** [comment]
@sabina1997 your main example should work?

**Comment by sabina1997** [comment]
No it doesnt work

**Comment by sabina1997** [comment]
<img width="530" alt="Screenshot 2020-04-17 at 6 51 09 PM" src="https://user-images.githubusercontent.com/41695168/79594130-cb49e700-80dc-11ea-9896-e8642343b32d.png">

**Comment by vmanot** [comment]
The following code works for me, I'm not sure what I'm missing here:

<img width="723" alt="Screen Shot 2020-04-18 at 2 54 21 AM" src="https://user-images.githubusercontent.com/5306992/79615231-e8ec7000-811f-11ea-9d14-44f6bde1197e.png">

```
struct ContentView: View {
    var body: some View {
        PaginationView {
            ForEach([1, 2, 3], id: \.hashValue) {
                Text(String($0))
            }
        }
    }
}
```

Which version of Xcode are you using? Maybe your SPM package resolution is out of date? You should essentially see the following `init` in the generated interface for the SwiftUIX module:

<img width="1038" alt="Screen Shot 2020-04-18 at 2 55 41 AM" src="https://user-images.githubusercontent.com/5306992/79615312-189b7800-8120-11ea-9ce0-6e893693ed2a.png">

**Comment by sabina1997** [comment]
I just updated xcode to check if that was the problem. Now Im getting two errors

<img width="768" alt="Screenshot 2020-04-18 at 9 10 23 PM" src="https://user-images.githubusercontent.com/41695168/79669030-1f29fe00-81b9-11ea-897f-08630ea8c0d6.png">

**Comment by sabina1997** [comment]
I realised that the extension you said is missing, reinstalled again the package from master but the same. Am I missing something?

**Comment by sabina1997** [comment]
@vmanot I found the problem, when I get the package with branch master, I didnt get the updates, I tried with commit and now its working , thanks
