### ISSUE TITLE
Last update 0.2.2 broke project < iOS 17

### ISSUE THREAD

**Issue by corentios** [SwiftUIX/SwiftUIX#501]
Hello, got this error in project supporting < iOS 17 : 

❌  SwiftUIX/Sources/SwiftUIX/Intermodular/Extensions/Dispatch/DispatchQueue++.swift:19:31: 'assumeIsolated(_:file:line:)' is only available in iOS 17.0 or newer
                    MainActor.assumeIsolated {
^
❌  SwiftUIX/Intermodular/Extensions/Dispatch/DispatchQueue++.swift:29:23: 'assumeIsolated(_:file:line:)' is only available in iOS 17.0 or newer
            MainActor.assumeIsolated {
^

**Comment by rrenna** [comment]
Seeing the same issue.
