### ISSUE TITLE
PaginationView auto height

### ISSUE THREAD

**Issue by welove** [SwiftUIX/SwiftUIX#53]
Is there a way to detect the height of the tallest view inside the PaginationView and make it its frame height?
Also, is it possible to make an "Auto Play" so it behaves like a slideshow?

**Comment by vmanot** [comment]
@welove implementing auto-play is out of scope for this project, you can easily achieve this via a `Timer` and `PaginationView.currentPageIndex`. Automatic resizing is something that has been requested quite a bit, I'll see if I can squeeze it in sometime in the near future :)

**Comment by welove** [comment]
Perfect :) Congratulations on the project. Its awesome! 👏

**Comment by welove** [comment]
Hello, I have a Binding like this: .currentPageIndex(self.$currentImageIndex)

When I set a new value for the currentImageIndex, the PaginationView changes to the correct page, but the pagination dots don't change.
Do I need to keep them in sync manually or is it a possible bug?

**Comment by welove** [comment]
Hello, this auto height feature would be really useful.
Right now I have a paginating view with text and images, and I have to set heights for iPhones and iPads, each of them a different height for portrait or landscape, each iPhone and iPad have different sizes witch can make a text multiline or not, not to count when the app can be in a split view when multitasking on the iPad. Pleeeeeease make this happen :)

**Comment by vmanot** [comment]
@welove taking a look at it - hopefully I can solve it today.

**Comment by vmanot** [comment]
@welove could we discuss this? I'm unsure as to what behavior you want with `PaginationView`. Dynamically changing height based on content seems a bit jarring - do you want the maximum height selected?

**Comment by welove** [comment]
I believe the best solution is to assume the height of the tallest page of all. That way is guaranteed that no content gets clipped/cut

**Comment by welove** [comment]
Hello, any progress on this? I'm almost launching an app and this update would be very welcome 🙏

**Comment by vmanot** [comment]
@welove I really can't figure out how to get this to work - calculating and setting `view.frame.size`on the underlying `UIPageViewController` doesn't seem to work :/

**Comment by vmanot** [comment]
Closing this issue as I don't know how to fix this - or even the best API. Please reopen if you have any workarounds, and/or raise a PR.
