### ISSUE TITLE
Checkbox images

### ISSUE THREAD

**Issue by welove** [SwiftUIX/SwiftUIX#56]
I think it's more intuitive if the checkbox used an empty square image when off ("square" instead of "checkmark.square").

When we have multiple checkboxes and none of them is on, it feels like they're all checked by default.

Can you please update or give us the option to choose which symbol to use?

<img width="139" alt="Captura de ecrã 2020-04-27, às 17 45 07" src="https://user-images.githubusercontent.com/1217162/80397959-dbb54b00-88ae-11ea-98f7-d9dd30e4cb1e.png">

**Comment by vmanot** [comment]
You can now implement custom checkbox styles in a fashion similar to `ButtonStyle`:

```swift
public struct DefaultCheckboxStyle: CheckboxStyle {
    public func makeBody(configuration: CheckboxStyleConfiguration) -> some View {
        HStack {
            configuration.label
            
            configuration.isSelected
                ? Image(systemName: .checkmarkSquareFill)
                : Image(systemName: .checkmarkSquare)
        }
    }
}
```

(/¯–‿･)/¯
