### ISSUE TITLE
PaginationView index

### ISSUE THREAD

**Issue by yonaskolb** [SwiftUIX/SwiftUIX#58]
Hi, great library!
Currently when updating the `PaginationView` index programmatically with `currentPageIndex` the page control dots don't change and also get out of sync with the index if you switch to swiping

**Comment by lorenzofiamingo** [comment]
Can you post your code? I'm using it as well and is working fine

**Comment by vmanot** [comment]
@yonaskolb this bug was recently fixed (see #57). Is it possible that you're not on the latest commit of `master`?

**Comment by vmanot** [comment]
Closing this as there's been no reply for a couple of days - feel free to reopen if the issue persists!

**Comment by yonaskolb** [comment]
Hi @vmanot, I ended up moving to https://github.com/fermoya/SwiftUIPager for this particular component, so I don't have the code around anymore. Sorry for not getting back to you earlier. 

At the time I'm pretty sure I was on the latest master, because I updated to see if the issue was fixed, but maybe the update didn't take properly 🤷‍♂️
I'm sure someone else will raise it though if it's still an issue 👍
