### ISSUE TITLE
Setting CocoaList's contentOffset

### ISSUE THREAD

**Issue by riccardo-lomazzi** [SwiftUIX/SwiftUIX#63]
I'd like to save the scroll offset of a `CocoaList` while navigating through pages.

I thought it was possible by using the `onOffsetChange` modifier, but the exposed `ScrollView<AnyView>.ContentOffset` argument doesn't let you get the `contentOffset` property as it seems to be declared as `fileprivate`. 
I've tried creating a `extension CocoaList` with a custom method to get it, but the compiler tells me that the property is set as `internal`.

Also, I'd like to set the `contentOffset` back to where it was after navigating towards a page, but it seems there is no public `setContentOffset`: there's one in `UIHostingTableViewController`, but it isn't accessible.

Is there a way to currently do the things above?

Thanks in advance for any clarification.

**Comment by vmanot** [comment]
@riccardo-lomazzi support for this feature is underway, I expect it to be done in a couple of days.

**Comment by vmanot** [comment]
@riccardo-lomazzi `CocoaList` now supports a `contentOffset(_:)` modifier, and accepts a `Binding<CGPoint>`.

See [this tweet](https://twitter.com/vatsal_manot/status/1264154161093861376?s=20) for a demo.

**Comment by riccardo-lomazzi** [comment]
Splendid, thanks a lot!

**Comment by vmanot** [comment]
@riccardo-lomazzi I'm slightly concerned about the implementation (performance-wise), so please update me if you notice any oddities.
