### ISSUE TITLE
Navigation Bar size

### ISSUE THREAD

**Issue by KALIMI** [SwiftUIX/SwiftUIX#64]
<img width="1440" alt="Screen Shot 2020-05-11 at 01 12 52" src="https://user-images.githubusercontent.com/46112191/81510665-9b30e500-9324-11ea-8a22-1eededa0d2c7.png">
The content is not available to place on its place. the view is giving extra space

**Comment by vmanot** [comment]
Try using `.fixedSize()`?

**Comment by KALIMI** [comment]
It didn't help

**Comment by KALIMI** [comment]
But it works good on child views of this navigation view

**Comment by vmanot** [comment]
@KALIMI that's very weird :( 

Could you upload an example project reproducing this issue?
