### ISSUE TITLE
Navigating a Page Control

### ISSUE THREAD

**Issue by writing-shed** [SwiftUIX/SwiftUIX#66]
I have used PaginationControl with a ForEach view. I would like to add control buttons to navigate between views. Is this possible, and if it is, how?

**Comment by vmanot** [comment]
@writing-shed check out `PreviousButton` and `NextButton`. `PaginationView` exposes something called a `ProgressionController` which can be used to move to next/previous.

**Comment by writing-shed** [comment]
Thanks for this. I have tried it but found that the environment variable is set to nil. Here's my code:

struct TextEditView: View {
    @Environment(\.progressionController) var progressionController
    var text:String
    var ranges:PageRanges
    var body: some View {
        VStack {
            HStack {
                PreviousButton(action: {
                    self.progressionController?.moveToPrevious()
                }) {
                    Text("previous")
                }
                NextButton(action: {
                    self.progressionController?.moveToNext()
                })
                {
                    Text("next")
                }
            }
            PaginationView(axis: .horizontal, transitionStyle: .scroll, showsIndicators: false) {
                ForEach(ranges, id:\.id) { pageRange in
                    VStack {
                        TextView(text: self.text, range: pageRange)
                        Text("page \(pageRange.page)")
                    }
                    
                }
            }
        }
    }
}

**Comment by vmanot** [comment]
@writing-shed apologies for not seeing the comment! `PreviousButton` and `NextButton` are meant to be used _within_ `PaginationView ` content.

If you want to control pagination from _outside_, you have to maintain a `@State` variable for your current page index and pass it to `PaginationView`'s `currentPageIndex(_:)` modifier. 

Reopening until its completely resolved :)

**Comment by writing-shed** [comment]
Thanks very much.
