### ISSUE TITLE
The content in CocoaScrollView is not displayed.

### ISSUE THREAD

**Issue by fatbobman** [SwiftUIX/SwiftUIX#67]
The content in CocoaScrollView is not displayed.
I'm using the latest version

```swift
struct Test: View {
  var body: some View {
      CocoaScrollView {
        VStack {
          ForEach(0..<200) { i in
            Text(String(i))
              .foregroundColor(.black)
          }
        }
      }
    }
}
```

**Comment by vmanot** [comment]
@fatbobman adding `.fixedSize()` seems to have solved the problem for me - but this is weird, I'll investigate it!

**Comment by fatbobman** [comment]
After adding .fixedSize() I can now see the content. However, this requires specifying the width of the Cell.
after using .frame I got the same solution.
```swift
struct Test: View {
  var body: some View {
      CocoaScrollView {
        VStack(alignment: .center) {
          ForEach(0..<100) { i in
            HStack(alignment: .center){
                Spacer()
                Text(String(i))
                Spacer()
            }
            .frame(width:UIScreen.main.bounds.width)
          }
        }
    }
   }
}
```
Expect a complete resolution.
Thank you for doing such an excellent project.

**Comment by vmanot** [comment]
This cannot be fixed without using `fixedSize()` unfortunately, I'm not aware of a workaround. If you do find one, please do let me know and/or open up a PR!
