### ISSUE TITLE
ImagePicker

### ISSUE THREAD

**Issue by writing-shed** [SwiftUIX/SwiftUIX#68]
It would be nice if you could  #add the option to choose the SourceType on the interface rather than hardwire it to .photoLibrary.

BTW You haven't responded to my comment on issue #66 (which you had closed).

**Comment by vmanot** [comment]
@writing-shed done! Funnily enough - I'd already coded support for this but forgot to expose it via a modifier. Thanks for bringing it up.
<img width="1252" alt="Screen Shot 2020-05-21 at 5 47 06 PM" src="https://user-images.githubusercontent.com/5306992/82558363-18612300-9b8b-11ea-94de-868276ebf105.png">

**Comment by writing-shed** [comment]
Thanks. I'm no GitHub expert - will you be updating the package?

**Comment by vmanot** [comment]
@writing-shed I've already pushed the change. To update in Xcode:

**Select File ▸ Swift Packages ▸ Update to Latest Package Versions**

**Comment by writing-shed** [comment]
OK, got it. Thanks very much.
