### ISSUE TITLE
NavigationBar custom View gesture bug 

### ISSUE THREAD

**Issue by RobertKoval** [SwiftUIX/SwiftUIX#70]
```
.navigationBarTitleView(
HStack {
    Text(title)
    Image(systemName: "chevron.down")
}.onTapGesture {
    self.isPopUpPresented = true
}
, displayMode: .inline)
```

When I click first time on the label, pop-up is presented. Inside pop-up I select the option which changes **title** state and closes itself, after that title view stops responding to tap gestures.

**Comment by vmanot** [comment]
I'll take a look, thanks for pointing it out.

**Comment by RobertKoval** [comment]
it's related to: https://stackoverflow.com/questions/58512344/swiftui-navigation-bar-button-not-clickable-after-sheet-has-been-presented

**Comment by vmanot** [comment]
@RobertKoval I'm marking this as an Apple bug then.
