### ISSUE TITLE
XCode 11.5 Archive Issue

### ISSUE THREAD

**Issue by vicky-ghost** [SwiftUIX/SwiftUIX#73]
<img width="644" alt="Screenshot 2020-05-23 at 10 14 37 PM" src="https://user-images.githubusercontent.com/65822824/82735890-d24ebf80-9d42-11ea-9121-ef7e9f00f072.png">

**Comment by vmanot** [comment]
@vicky-ghost project archives successfully on my end (Xcode 11.5 GM). Try weak linking SwiftUIX to your app - it's an issue with the Swift compiler's library linker, not SwiftUIX.

**Comment by vicky-ghost** [comment]
@vmanot  Weak linking did not help, Did you try XCode 11.5 Public Release?
