### ISSUE TITLE
ObservedPublisher for CurrentValueSubject

### ISSUE THREAD

**Issue by fatbobman** [SwiftUIX/SwiftUIX#75]
ObservedPublisher is a great solution that combines @State and onRecevie into one. But when using CurrentValueSubject there is a problem, ObservedPublisher ignores dropping the first value.
I added a line to the code and now it adapts nicely to CurrentValueSubject.

```swift
self._subscription = .init(initialValue: publisher
       .delay(for: .nanoseconds(1), scheduler: RunLoop.main)
       .sink(receiveValue: {
            updateWrappedValue.value($0)
        }))
```

**Comment by vmanot** [comment]
@fatbobman this is a great catch, and I actually faced the exact same problem while initially writing it! 

Very neat workaround, just trying to think of any possible downsides. Could you also think about any potential problems with the delay? I'd be inclined to accept this solution and incorporate it immediately, except I've been burnt by optimistic reactive programming one too many times :p

**Comment by fatbobman** [comment]
Okay. Since I'll be using this scheme for my own projects, I'll be watching closely and continuing to study it. The biggest pitfall at the moment is that the internal implementation mechanism of Combine is still unstable and may be subject to constant change.

**Comment by vmanot** [comment]
@fatbobman how about this instead?:

```swift
        self._subscription = .init(
            initialValue: Publishers.Concatenate(
                prefix: Just(initial)
                    .delay(for: .nanoseconds(1), scheduler: RunLoop.main),
                suffix: publisher
            ).sink(receiveValue: {
                updateWrappedValue.value($0)
            })
        )
```

The reason I'm hesitant to use the initial solution is because it's a constant `delay` applied to the publisher. I know, it's just one nanosecond, but it's the difference between synchronous and asynchronous - i.e. additional overhead.

**Comment by fatbobman** [comment]
Good solution！ The logic is also clearer.

**Comment by vmanot** [comment]
@fatbobman could you see if this works for you, in your projects? I'm testing here as well.

**Comment by fatbobman** [comment]
@vmanot I've tested it and it runs well in my project.

**Comment by vmanot** [comment]
@fatbobman implemented. Thanks again!

**Comment by JackYoustra** [comment]
Could you also use `dropFirst`?
