### ISSUE TITLE
PaginationView and currentPageIndex

### ISSUE THREAD

**Issue by writing-shed** [SwiftUIX/SwiftUIX#76]
Further to my recent PaginationView issue I would like to get the current page number, but can't see a way of achieving this. Is there one?

**Comment by vmanot** [comment]
@writing-shed `currentPageIndex` takes a `Binding<Int>`. This `Binding` is bidirectional. When you modify the `@State` behind this binding, `PaginationView` reacts, and when the user swipes manually, the current page index is written back to the same `Binding<Int>` passed. Your `@State` and the internal page view controller state are kept in sync at all times.

**Comment by writing-shed** [comment]
Yes, but what is the receiver for currentPageIndex? It seems to want PaginationView<Page> and I can't figure out how to save that.

**Comment by vmanot** [comment]
@writing-shed tad confused by the problem you're facing, but let illustrate what I meant with an example:

```swift
struct Foo: View {
    @State var currentPageIndex: Int = 0
    
    var body: some View {
        PaginationView {
            Text("1")
            Text("2")
            Text("3")
        }
        .currentPageIndex($currentPageIndex)
    }
}
```

**Comment by vmanot** [comment]
`@State var currentPageIndex` here is always synced with whatever the user decides to swipe/jump to. Even if you never end up setting `currentPageIndex` programmatically, it still serves as a way for `PaginationView` to record what the current page index is.

**Comment by writing-shed** [comment]
I just tried it with the following, but the page num doesn't change?

struct PaginatedView: View {
    var text:NSAttributedString
    var ranges:PageRanges
    @State private var rect: CGRect = CGRect()
    @State var pageNum = 0

    var body: some View {
        VStack {
            PaginationView(axis: .horizontal, transitionStyle: .pageCurl, showsIndicators: false) {
                ForEach(ranges, id:\.id) { pageRange in
                    PageView(text:self.text, ranges: self.ranges, pageRange: pageRange, pageNum: self.pageNum)
                }
            }.currentPageIndex($pageNum)
        }
    }
}

struct PageView:View {
    var text:NSAttributedString
    var ranges:PageRanges
    var pageRange:PageRange
    var pageNum:Int

    var body: some View {
        VStack {
            HStack {
                Spacer()
                PageLeft()
                
                Text("Page \(pageNum)")
                                
                PageRight()
                Spacer()
            }
            GeometryReader { geo in
                TextPageView(text: self.text, range: self.pageRange, size:geo.size)
            }
        }
    }
}
    

struct PageRight: View {
    @Environment(\.progressionController) var progressionController
    
    var body: some View {
        Button(action: {
            self.progressionController?.moveToNext()
        }) {
            Image(systemName: "chevron.right")
        }.padding().imageScale(.large)
    }
}

struct PageLeft: View {
    @Environment(\.progressionController) var progressionController
    
    var body: some View {
        Button(action: {
            self.progressionController?.moveToPrevious()
        }) {
            Image(systemName: "chevron.left")
        }.padding().imageScale(.large)
    }
}

**Comment by writing-shed** [comment]
Sorry, the number does change when I swipe, but not when I tap on the buttons.

Also, how can I change the number if I add buttons to jump to the first/last page?

**Comment by vmanot** [comment]
This is a bug! Fixing it right now, give me a couple of minutes.

**Comment by vmanot** [comment]
@writing-shed fixed!

**Comment by vmanot** [comment]
![Pagination](https://user-images.githubusercontent.com/5306992/82926990-9f543800-9f9d-11ea-88c0-6e4025cc80f8.gif)

```swift

struct SamplePage: View {
    let index: Int
    
    var body: some View {
        HStack {
            PreviousButton() {
                Text("Previous")
            }
            
            Text("\(index)")
            
            NextButton() {
                Text("Next")
            }
        }
    }
}

struct SamplePages: View {
    @State var currentPageIndex: Int = 0
    
    var body: some View {
        VStack {
            Text("Current Page Index: \(currentPageIndex)")
                .padding(.top)
            
            PaginationView {
                SamplePage(index: 0)
                SamplePage(index: 1)
                SamplePage(index: 2)
                SamplePage(index: 3)
                SamplePage(index: 4)
            }
            .currentPageIndex($currentPageIndex)
            .padding()
            .backgroundColor(Color.quaternarySystemFill)
        }
    }
}
```

**Comment by vmanot** [comment]
@writing-shed let me know if this has solved your problem - so that I can close this issue.

**Comment by writing-shed** [comment]
Your solution is OK when the pages are listed, but not if the ForEach option is selected, unless I'm missing something. Here's what I've got now:

struct PaginatedView: View {
    var text:NSAttributedString
    var ranges:PageRanges
    @State private var rect: CGRect = CGRect()
    @State var pageNum = 1

    var body: some View {
        VStack {
            PaginationView(axis: .horizontal, transitionStyle: .pageCurl, showsIndicators: false) {
                ForEach(ranges, id:\.id) { pageRange in
                    PageView(text:self.text, ranges: self.ranges, pageRange: pageRange, pageNum: self.$pageNum)
                }
            }.currentPageIndex($pageNum)
        }
    }
}

struct PageView:View {
    var text:NSAttributedString
    var ranges:PageRanges
    var pageRange:PageRange
    @Binding var pageNum:Int

    var body: some View {
        VStack {
            HStack {
                Spacer()
                PageLeft(page: self.$pageNum).isHidden(self.pageNum == 1)
                
                Text("Page \(pageNum)")
                                
                PageRight(page: self.$pageNum).isHidden(self.pageNum == ranges.count - 1)
                Spacer()
            }
            GeometryReader { geo in
                TextPageView(text: self.text, range: self.pageRange, size:geo.size)
            }
        }
    }
}
    

struct PageRight: View {
    @Environment(\.progressionController) var progressionController
    @Binding var page:Int

    var body: some View {
        Button(action: {
            self.progressionController?.moveToNext()
            self.$page.wrappedValue = self.page + 1
        }) {
            Image(systemName: "chevron.right")
        }.padding().imageScale(.large)
    }
}

struct PageLeft: View {
    @Environment(\.progressionController) var progressionController
    @Binding var page:Int
    
    var body: some View {
        Button(action: {
            self.progressionController?.moveToPrevious()
            self.$page.wrappedValue = self.page - 1
        }) {
            Image(systemName: "chevron.left")
        }.padding().imageScale(.large)
    }
}

**Comment by vmanot** [comment]
@writing-shed one problem I see here is duplicate modifications to the page state variable:

```
            self.progressionController?.moveToNext()
            self.$page.wrappedValue = self.page + 1
```

`moveToNext()` will already increment the `Binding<Int>` for you.

**Comment by vmanot** [comment]
@writing-shed `PageRight` and `PageLeft` can be re-expressed using SwiftUIX primitives as such:

```swift
struct PageRight: View {
    var body: some View {
        PreviousButton {
            Image(systemName: "chevron.right")
                .padding()
                .imageScale(.large)
        }
    }
}

struct PageLeft: View {
    var body: some View {
        PreviousButton {
            Image(systemName: "chevron.left")
                .padding()
                .imageScale(.large)
        }
    }
}
```

**Comment by writing-shed** [comment]
Brilliant. I should have twigged that they use ProgessionController. Thanks. All works well now.
