### ISSUE TITLE
Build errors in watchOS and tvOS

### ISSUE THREAD

**Issue by BenSova** [SwiftUIX/SwiftUIX#79]
**watchOS**
This error came up where you were calling an extension to `AppKitOrUIKitHostingControllerProtocol`. I noticed that most of the file is hidden from watchOS, except for this extension, though. You can probably solve this by hiding the extension from watchOS.
```Swift
#if !os(watchOS) // Add this
extension AppKitOrUIKitHostingControllerProtocol {
    // ...
}
#endif // And this
```

**tvOS**
This one came up at `if base?.isPagingEnabled ?? false` (Under `_UIHostingScrollViewRootView`).

**Errors**
watchOS
```js
.../Sources/Intermodular/Helpers/AppKit or UIKit/AppKitOrUIKitHostingControllerProtocol.swift:38:11: Use of undeclared type 'AppKitOrUIKitHostingControllerProtocol'
```
tvOS
```js
.../Sources/Intermodular/Helpers/UIKit/UIHostingScrollView.swift:192:22: 'isPagingEnabled' is unavailable in tvOS
```

**Comment by vmanot** [comment]
@BenSova fixed, thank you for raising the issue!
