### ISSUE TITLE
Cannot contribute to the wiki

### ISSUE THREAD

**Issue by kitwtnb** [SwiftUIX/SwiftUIX#80]
This library is great, but not enough documented.  
How do I editing document in the Wiki?

**Comment by BenSova** [comment]
@kitwtnb, as of right now, the wiki requires you to have push access to edit it, so @vmanot would have to add you as a contributor.
However, you could probably:
-  Clone the wiki to your computer (https://github.com/SwiftUIX/SwiftUIX.wiki.git)
- Make some changes.
- Upload the files, vmanot can add them to the wiki.

**Comment by vmanot** [comment]
@kitwtnb feel free to raise a PR with the documentation in the README - I'll move it to the wiki. Not ideal - but unfortunately GitHub wikis do not support raising/merging PRs.

**Comment by BenSova** [comment]
Another suggestion, what if there was a docs folder that is a mirror of the wiki? Then, it'd be a little bit more practical, and the wiki could be accessed easier by anyone who has the repo on their computer.

**Comment by vmanot** [comment]
@BenSova I think I found a solution! - https://github.com/marketplace/actions/publish-to-github-wiki

**Comment by BenSova** [comment]
@kitwtnb Just so you know, vmanot found a solution that works with my idea of a docs folder. (See #81 for more).

**Comment by kitwtnb** [comment]
Thanks for @BenSova !  
I will documentation.

**Comment by BenSova** [comment]
@vmanot Would you like me to hold on to my fork? I looked over the code of the action and it appears to need the wiki already inside the code, otherwise it might wipe the wiki (just a guess).

**Comment by vmanot** [comment]
@BenSova sorry for the late reply, been busy with a couple of things. You can discard the fork, it's just a trivial matter of cloning the wiki myself. Will do it all at once when I set up the action(s). 

Thanks again :)

**Comment by vmanot** [comment]
SwiftUIX now has a "Guides" folder, and is also shifting first level/summary documentation to its README.
