### ISSUE TITLE
UIPageViewControllerOptionsKey

### ISSUE THREAD

**Issue by yyl0** [SwiftUIX/SwiftUIX#84]
is there a way to insert UIPageViewControllerOptionsKey for spacing between paging view items in the init? i am using this from swift package manager

**Comment by vmanot** [comment]
@yyl0 I'll look into adding support, thanks for raising the issue.

**Comment by vmanot** [comment]
@yyl0 you can now set `interPageSpacing` via the `PaginationView.interPageSpacing(_:)` modifier.

**Comment by yyl0** [comment]
awesome thanks man!! keep up the great work
