### ISSUE TITLE
BlurEffectView & VisualEffectView Examples?

### ISSUE THREAD

**Issue by ismyhc** [SwiftUIX/SwiftUIX#86]
Hi, could someone point me in the right direction to using the BlurEffectView & VisualEffectView's?

Id like to create a view here the background is a BlurEffectView.

Thanks for any help :)

**Comment by vmanot** [comment]
@ismyhc documentation is coming up soon! Apologies for the delayed reply, WWDC-week has been crazy!

**Comment by hactar** [comment]
Also can't figure this out.

I can get BlurEffectView to work (though if I put a Text in the content the BlurEffectView does not hug the content but fills the screen - only workaround I have found is using it in the .background of the Text).

If I try to use the VibrancyEffectView the way I'd expect it to work, I only see the Text Label in black with no system material or vibrancy effect.

```
struct ExperimentalView: View {
    var body: some View {
        ZStack {
            Image("map")
            VibrancyEffectView(blurStyle: .systemMaterial, vibrancyStyle: .label) {
                Text("Test Text")
            }
        }

    }
}
```

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-02 at 19 15 57](https://user-images.githubusercontent.com/645674/89128248-a72bdd80-d4f4-11ea-8eaf-811e61c24c78.png)

**Comment by vmanot** [comment]
Done.
