### ISSUE TITLE
Another PaginationView issue

### ISSUE THREAD

**Issue by writing-shed** [SwiftUIX/SwiftUIX#92]
After thinking it was all working it I've discovered another issue. For reasons I can't figure out it always displays page 2 first instead of page 1. Here's the code (using Xcode 11). I can see it step through the ForEach with pageRange set ok, but then the first time it gets to TextPageView it passes the second pageRange with page = 2:

struct PaginatedView: View {
    var text:NSAttributedString
    var ranges:PageRanges
    var orientationSubscriber:OrientationSubscriber
    @State private var rect: CGRect = CGRect()
    @State var pageNum = 1

    var body: some View {
        VStack {
            PaginationView(axis: .horizontal, transitionStyle: .pageCurl, showsIndicators: false) {
                ForEach(ranges, id:\.id) { pageRange in
                    PageView(text:self.text,
                             ranges: self.ranges,
                             pageRange: pageRange,
                             orientationSubscriber: self.orientationSubscriber)
                }
            }.currentPageIndex($pageNum)
        }
    }
}

struct PageView:View {
    var text:NSAttributedString
    var ranges:PageRanges
    var pageRange:PageRange
    var orientationSubscriber:OrientationSubscriber

    var body: some View {
        VStack {
            HStack {
                Spacer()
                PageLeft().isHidden(self.pageRange.page == 1)
                
                Text("Page \(self.pageRange.page)")
                                
                PageRight().isHidden(self.pageRange.page == ranges.count)
                Spacer()
            }
            GeometryReader { geo in
                TextPageView(text: self.text,
                             range: self.pageRange,
                             size:geo.size,
                             orientationSubscriber: self.orientationSubscriber)
            }
        }
    }
}
    

struct PageRight: View {
    @Environment(\.progressionController) var progressionController

    var body: some View {
        Button(action: {
            self.progressionController?.moveToNext()
        }) {
            Image(systemName: "chevron.right")
        }.padding().imageScale(.large)
    }
}

struct PageLeft: View {
    @Environment(\.progressionController) var progressionController
    
    var body: some View {
        Button(action: {
            self.progressionController?.moveToPrevious()
        }) {
            Image(systemName: "chevron.left")
        }.padding().imageScale(.large)
    }
}

**Comment by writing-shed** [comment]
Doh! It's because pageNum is initialised to 1 not 0.

**Comment by vmanot** [comment]
@writing-shed happens to the best of us :)
