### ISSUE TITLE
NavigationLink not working inside CocoaScrollView

### ISSUE THREAD

**Issue by PKizzle** [SwiftUIX/SwiftUIX#97]
Any NavigationLink placed inside a CocoaScrollView will not redirect to its destination.
The destination view seems to get loaded, but the visual redirect does not happen.

**Comment by vmanot** [comment]
@PKizzle is this on iOS 14?

**Comment by PKizzle** [comment]
Yes, exactly.

**Comment by vmanot** [comment]
@PKizzle hmm, that's weird. Then again, `NavigationLink` has always been an odd fellow. File a bug for iOS 14 beta, maybe? Let me know if you do file it, I'll dupe. 

It's definitely an Apple bug, because `CocoaScrollView` is using no private APIs.

**Comment by PKizzle** [comment]
How can I share a bug report with you? I guess there is only the Feedback assistant nowadays?

**Comment by vmanot** [comment]
@PKizzle even earlier there was no way to share a report with someone else :/ 

Just copy paste the title, body and feedback number of your report here, I'll create a new feedback report and file it myself.

**Comment by PKizzle** [comment]
One thing that is strange: I tested another `UIScrollView` implementation which directly makes use of it (without a ?`UIHostingScrollView`) and there it seems to work
What does not work: Using it with your custom `UIHostingScrollView` or using an `UIViewControllerRepresentable`

**Comment by PKizzle** [comment]
**Please provide a descriptive title for your feedback:**
`NavigationLinks do not work inside UIScrollView`

**Which area are you seeing an issue with?**
`SwiftUI-Framework`

**What type of feedback are you reporting?**
`Incorrect / unexpected behavior`

**Please describe the issue:**
`When using a NavigationLink inside a UIScrollView which is interfacing using a UIViewRepresentable, the NavigationLink will not redirect to the destination.
A UIViewControllerRepresentable will also not work.`

**Please list the steps you took to reproduce the issue:**
`1. Use a CocoaScrollView from https://github.com/SwiftUIX/SwiftUIX as an example
2. Place a NavigationLink with a dummy destination (e.g. Text(„Test“)) inside
3. Compile and try to click on the NavigationLink`

**What did you expect to happen?**
`The NavigationLink should correctly redirect to the destination.`

**What actually happened?**
`No redirection happens and the NavigationLink is not clickable.`

**Comment by vmanot** [comment]
@PKizzle could you link that working implementation? Using `UIScrollView`?

**Comment by PKizzle** [comment]
Using LegacyScrollView found here: https://stackoverflow.com/a/60168697/10969681

```
import Foundation
import SwiftUI

struct LegacyScrollView: UIViewRepresentable {
    enum Action {
        case idle
        case offset(x: CGFloat, y: CGFloat, animated: Bool)
    }

    @Binding var action: Action
    private let uiScrollView: UIScrollView

    init<Content: View>(content: Content) {
        let hosting = UIHostingController(rootView: content)
        hosting.view.translatesAutoresizingMaskIntoConstraints = false

        uiScrollView = UIScrollView()
        uiScrollView.addSubview(hosting.view)

        let constraints = [
            hosting.view.leadingAnchor.constraint(equalTo: uiScrollView.leadingAnchor),
            hosting.view.trailingAnchor.constraint(equalTo: uiScrollView.trailingAnchor),
            hosting.view.topAnchor.constraint(equalTo: uiScrollView.contentLayoutGuide.topAnchor),
            hosting.view.bottomAnchor.constraint(equalTo: uiScrollView.contentLayoutGuide.bottomAnchor),
            hosting.view.widthAnchor.constraint(equalTo: uiScrollView.widthAnchor)
        ]
        uiScrollView.addConstraints(constraints)

        self._action = Binding.constant(Action.idle)
    }

    init<Content: View>(@ViewBuilder content: () -> Content) {
        self.init(content: content())
    }

    init<Content: View>(action: Binding<Action>, @ViewBuilder content: () -> Content) {
        self.init(content: content())
        self._action = action
    }

    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }

    func makeUIView(context: Context) -> UIScrollView {
        return uiScrollView
    }

    func updateUIView(_ uiView: UIScrollView, context: Context) {
        switch self.action {
        case .offset(let x, let y, let animated):
            uiView.setContentOffset(CGPoint(x: x, y: y), animated: animated)
            DispatchQueue.main.async {
                self.action = .idle
            }
        default:
            break
        }
    }

    class Coordinator: NSObject {
        let legacyScrollView: LegacyScrollView

        init(_ legacyScrollView: LegacyScrollView) {
            self.legacyScrollView = legacyScrollView
        }
    }

}


struct TestView: View {
    var body: some View {
        NavigationView {
            LegacyScrollView {
                NavigationLink(destination: Text("Other view"), label: { Text("Click me") })
            }
        }
    }
}
```

**Comment by vmanot** [comment]
No idea why `NavigationLink` won't work within `CocoaScrollView`, I tried a bunch of different techniques. I've faced similar issues with environment objects/environment keys not being propagated down through representables. Please keep filing bugs, and hope they fix it :(

**Comment by BugMonkey** [comment]
![image](https://user-images.githubusercontent.com/22151098/155474018-b15e2b31-6654-4565-80a0-c6f9041efd5b.png)
this is very weird，if use local variables，it works
