### ISSUE TITLE
onDismiss func be called when presented view

### ISSUE THREAD

**Issue by zsy78191** [SwiftUIX/SwiftUIX#99]
At AnyModalPresentation.swift file line 41 : 

```swift
        if let onPresent = onPresent {
            self.content = self.content.onPresent(perform: onPresent)
        }
        
        if let onDismiss = onDismiss {
            self.content = self.content.onPresent(perform: onDismiss)
        }
```
I think the second `onPresent` might be `onDismiss` , what lead that the onDismiss func be called when presented the view.

thanks for your excellent work.

**Comment by vmanot** [comment]
Fixed by your PR! Thank you for reporting and fixing :)
